/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddGroupMessageInput {
  'content' : string,
  'authorId' : bigint,
  'groupId' : bigint,
  'isVoiceMessage' : boolean,
}
export interface Alert {
  'id' : bigint,
  'alertType' : AlertType,
  'title' : string,
  'description' : string,
  'timestamp' : bigint,
  'severity' : AlertSeverity,
  'location' : string,
}
export type AlertSeverity = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null };
export type AlertType = { 'Pest' : null } |
  { 'Weather' : null };
export interface Answer {
  'id' : bigint,
  'content' : string,
  'upvoteCount' : bigint,
  'authorId' : bigint,
  'questionId' : bigint,
}
export interface AuditEvent {
  'action' : string,
  'performedBy' : string,
  'timestamp' : bigint,
}
export interface Certification {
  'id' : bigint,
  'title' : string,
  'badgeUrl' : string,
  'userId' : bigint,
  'issuedAt' : bigint,
  'courseId' : bigint,
}
export type ContractType = { 'None' : null } |
  { 'Phytosanitary' : null } |
  { 'Rental' : null };
export interface Conversation {
  'id' : bigint,
  'lastMessageAt' : bigint,
  'lastMessage' : string,
  'unreadCount' : bigint,
  'participantIds' : Array<bigint>,
}
export interface Course {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'createdAt' : bigint,
  'educatorId' : bigint,
  'description' : string,
  'level' : string,
  'durationMinutes' : bigint,
  'isCertified' : boolean,
  'category' : string,
  'rating' : number,
  'price' : number,
  'enrollmentCount' : bigint,
}
export interface CreateCourseInput {
  'title' : string,
  'thumbnailUrl' : string,
  'educatorId' : bigint,
  'description' : string,
  'level' : string,
  'durationMinutes' : bigint,
  'isCertified' : boolean,
  'category' : string,
  'price' : number,
}
export interface CreateDirectMessageInput {
  'content' : string,
  'isVoiceMessage' : boolean,
  'receiverId' : bigint,
  'senderId' : bigint,
}
export interface CreateEnrollmentInput {
  'userId' : bigint,
  'courseId' : bigint,
}
export interface CreateListingInput {
  'farmerId' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : ProduceCategory,
  'price' : number,
  'escrowEnabled' : boolean,
}
export interface CreateLiveStreamInput {
  'title' : string,
  'thumbnailUrl' : string,
  'description' : string,
  'hostId' : bigint,
  'scheduledAt' : bigint,
}
export interface CreateNotificationInput {
  'title' : string,
  'notifType' : NotifType,
  'body' : string,
  'userId' : bigint,
  'priority' : NotifPriority,
}
export interface CreateQuestionInput {
  'title' : string,
  'authorId' : bigint,
  'description' : string,
  'category' : string,
}
export interface CreateReelInput {
  'title' : string,
  'thumbnailUrl' : string,
  'farmerId' : bigint,
  'linkedListingId' : [] | [bigint],
}
export interface CreateSellerListingInput {
  'farmerId' : bigint,
  'name' : string,
  'contractType' : ContractType,
  'description' : string,
  'imageUrl' : string,
  'bulkUploadBatch' : string,
  'payoutSchedule' : PayoutSchedule,
  'category' : ProduceCategory,
  'certifications' : Array<string>,
  'price' : number,
  'escrowEnabled' : boolean,
  'verificationStatus' : VerificationStatus,
}
export interface DirectMessage {
  'id' : bigint,
  'content' : string,
  'isRead' : boolean,
  'isVoiceMessage' : boolean,
  'receiverId' : bigint,
  'timestamp' : bigint,
  'senderId' : bigint,
}
export interface DisputeCase {
  'id' : bigint,
  'status' : DisputeStatus,
  'resolution' : [] | [string],
  'orderId' : bigint,
  'evidence' : Array<string>,
  'timeline' : Array<DisputeEvent>,
}
export interface DisputeEvent {
  'event' : string,
  'performedBy' : string,
  'timestamp' : bigint,
}
export type DisputeStatus = { 'UnderReview' : null } |
  { 'Open' : null } |
  { 'Escalated' : null } |
  { 'Resolved' : null };
export interface Educator {
  'id' : bigint,
  'bio' : string,
  'courseCount' : bigint,
  'name' : string,
  'specialty' : string,
  'kycStatus' : KycStatus,
  'avatarUrl' : string,
  'rating' : number,
  'studentCount' : bigint,
}
export interface Enrollment {
  'id' : bigint,
  'completedAt' : [] | [bigint],
  'userId' : bigint,
  'progress' : number,
  'enrolledAt' : bigint,
  'courseId' : bigint,
}
export interface EquipmentGuide {
  'id' : bigint,
  'compatibility' : Array<string>,
  'equipmentName' : string,
  'maintenanceLog' : Array<MaintenanceEntry>,
}
export interface ExpertProfile {
  'id' : bigint,
  'name' : string,
  'hourlyRate' : number,
  'available' : boolean,
  'specialty' : string,
  'imageUrl' : string,
}
export interface Farmer {
  'id' : bigint,
  'bio' : string,
  'numListings' : bigint,
  'name' : string,
  'kycStatus' : KycStatus,
  'avatarUrl' : string,
  'rating' : number,
  'location' : string,
}
export interface ForumPost {
  'id' : bigint,
  'upvotes' : bigint,
  'title' : string,
  'body' : string,
  'author' : string,
  'replies' : Array<ForumReply>,
}
export interface ForumReply {
  'body' : string,
  'author' : string,
  'timestamp' : bigint,
}
export interface Group {
  'id' : bigint,
  'name' : string,
  'memberCount' : bigint,
  'description' : string,
  'iconUrl' : string,
}
export interface GroupMessage {
  'id' : bigint,
  'content' : string,
  'authorId' : bigint,
  'groupId' : bigint,
  'isVoiceMessage' : boolean,
  'timestamp' : bigint,
}
export interface InventoryItem {
  'id' : bigint,
  'threshold' : bigint,
  'listingId' : bigint,
  'forecastDays' : bigint,
  'currentStock' : bigint,
}
export interface KycRecord {
  'id' : bigint,
  'status' : KycVerificationStatus,
  'selfieVerified' : boolean,
  'idVerified' : boolean,
  'auditEvents' : Array<AuditEvent>,
  'userId' : bigint,
}
export type KycStatus = { 'Unverified' : null } |
  { 'Verified' : null } |
  { 'Pending' : null };
export type KycVerificationStatus = { 'Rejected' : null } |
  { 'Verified' : null } |
  { 'Pending' : null };
export interface Lesson {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'order' : bigint,
  'durationMinutes' : bigint,
  'videoUrl' : string,
  'courseId' : bigint,
}
export interface Listing {
  'id' : bigint,
  'farmerId' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'imageUrl' : string,
  'category' : ProduceCategory,
  'rating' : number,
  'price' : number,
  'escrowEnabled' : boolean,
}
export interface LiveStream {
  'id' : bigint,
  'status' : StreamStatus,
  'title' : string,
  'startedAt' : [] | [bigint],
  'thumbnailUrl' : string,
  'endedAt' : [] | [bigint],
  'description' : string,
  'hostId' : bigint,
  'viewerCount' : bigint,
  'scheduledAt' : bigint,
}
export interface LogisticsListing {
  'id' : bigint,
  'serviceArea' : string,
  'ratePerKm' : number,
  'imageUrl' : string,
  'providerName' : string,
}
export interface MachineryListing {
  'id' : bigint,
  'dailyRate' : number,
  'ownerId' : bigint,
  'name' : string,
  'available' : boolean,
  'imageUrl' : string,
  'category' : string,
}
export interface MaintenanceEntry {
  'technician' : string,
  'date' : bigint,
  'description' : string,
}
export interface MarketPrice {
  'id' : bigint,
  'region' : string,
  'crop' : string,
  'date' : bigint,
  'bidPrice' : number,
  'askPrice' : number,
}
export interface MarketPriceTick {
  'id' : bigint,
  'date' : bigint,
  'cropName' : string,
  'price' : number,
  'changePercent' : number,
}
export type NotifPriority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null };
export type NotifType = { 'SystemAlert' : null } |
  { 'Transaction' : null } |
  { 'MarketIntelligence' : null } |
  { 'Educational' : null } |
  { 'Emergency' : null };
export interface Notification {
  'id' : bigint,
  'title' : string,
  'notifType' : NotifType,
  'body' : string,
  'userId' : bigint,
  'createdAt' : bigint,
  'isRead' : boolean,
  'priority' : NotifPriority,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'total' : number,
  'listingId' : bigint,
  'createdAt' : bigint,
  'buyerId' : bigint,
  'quantity' : bigint,
}
export type OrderStatus = { 'Disputed' : null } |
  { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export type PayoutSchedule = { 'Net30' : null } |
  { 'Weekly' : null } |
  { 'Daily' : null };
export interface PlantingEntry {
  'id' : bigint,
  'plantDate' : bigint,
  'notes' : string,
  'cropName' : string,
  'harvestDate' : bigint,
}
export type ProduceCategory = { 'Eggs' : null } |
  { 'Grains' : null } |
  { 'Dairy' : null } |
  { 'Vegetables' : null } |
  { 'Other' : null } |
  { 'Fruits' : null };
export interface Question {
  'id' : bigint,
  'title' : string,
  'upvoteCount' : bigint,
  'authorId' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'answerCount' : bigint,
  'category' : string,
}
export interface Reel {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'farmerId' : bigint,
  'viewCount' : bigint,
  'linkedListingId' : [] | [bigint],
}
export interface SalesAnalytics {
  'id' : bigint,
  'period' : SalesPeriod,
  'cropName' : string,
  'totalRevenue' : number,
  'unitsSold' : bigint,
}
export type SalesPeriod = { 'Weekly' : null } |
  { 'Daily' : null } |
  { 'Monthly' : null } |
  { 'Yearly' : null };
export interface SeasonalAlert {
  'id' : bigint,
  'region' : string,
  'alertType' : SeasonalAlertType,
  'title' : string,
  'description' : string,
  'timestamp' : bigint,
  'cropName' : string,
  'severity' : AlertSeverity,
}
export type SeasonalAlertType = { 'Pest' : null } |
  { 'Price' : null } |
  { 'Weather' : null };
export interface SellerListing {
  'id' : bigint,
  'farmerId' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'contractType' : ContractType,
  'description' : string,
  'imageUrl' : string,
  'bulkUploadBatch' : string,
  'payoutSchedule' : PayoutSchedule,
  'category' : ProduceCategory,
  'rating' : number,
  'certifications' : Array<string>,
  'price' : number,
  'escrowEnabled' : boolean,
  'verificationStatus' : VerificationStatus,
}
export type StreamStatus = { 'Ended' : null } |
  { 'Live' : null } |
  { 'Scheduled' : null };
export interface SubmitOrderInput {
  'total' : number,
  'listingId' : bigint,
  'buyerId' : bigint,
  'quantity' : bigint,
}
export interface TeamMember {
  'id' : bigint,
  'permissions' : Array<string>,
  'name' : string,
  'role' : string,
  'lastActive' : bigint,
}
export type VerificationStatus = { 'Approved' : null } |
  { 'Expired' : null } |
  { 'Pending' : null };
export interface _SERVICE {
  'addGroupMessage' : ActorMethod<[AddGroupMessageInput], GroupMessage>,
  'add_dispute_case' : ActorMethod<[bigint, Array<string>], DisputeCase>,
  'add_forum_post' : ActorMethod<[string, string, string], ForumPost>,
  'add_kyc_record' : ActorMethod<[bigint], KycRecord>,
  'add_seller_listing' : ActorMethod<[CreateSellerListingInput], SellerListing>,
  'createCourse' : ActorMethod<[CreateCourseInput], Course>,
  'createListing' : ActorMethod<[CreateListingInput], Listing>,
  'createLiveStream' : ActorMethod<[CreateLiveStreamInput], LiveStream>,
  'createNotification' : ActorMethod<[CreateNotificationInput], Notification>,
  'createQuestion' : ActorMethod<[CreateQuestionInput], Question>,
  'createReel' : ActorMethod<[CreateReelInput], Reel>,
  'enrollInCourse' : ActorMethod<[CreateEnrollmentInput], Enrollment>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getAnswers' : ActorMethod<[bigint], Array<Answer>>,
  'getCertificationsByUser' : ActorMethod<[bigint], Array<Certification>>,
  'getConversations' : ActorMethod<[bigint], Array<Conversation>>,
  'getCourseById' : ActorMethod<[bigint], [] | [Course]>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getDirectMessages' : ActorMethod<[bigint], Array<DirectMessage>>,
  'getEducatorById' : ActorMethod<[bigint], [] | [Educator]>,
  'getEducators' : ActorMethod<[], Array<Educator>>,
  'getEnrollmentsByUser' : ActorMethod<[bigint], Array<Enrollment>>,
  'getFarmers' : ActorMethod<[], Array<Farmer>>,
  'getGroupMessages' : ActorMethod<[bigint], Array<GroupMessage>>,
  'getGroups' : ActorMethod<[], Array<Group>>,
  'getLessonsByCourse' : ActorMethod<[bigint], Array<Lesson>>,
  'getListings' : ActorMethod<[], Array<Listing>>,
  'getLiveStreams' : ActorMethod<[], Array<LiveStream>>,
  'getNotifications' : ActorMethod<[bigint], Array<Notification>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getQA' : ActorMethod<[], Array<Question>>,
  'getReels' : ActorMethod<[], Array<Reel>>,
  'getServices' : ActorMethod<
    [],
    {
      'logistics' : Array<LogisticsListing>,
      'experts' : Array<ExpertProfile>,
      'machinery' : Array<MachineryListing>,
    }
  >,
  'get_dispute_cases' : ActorMethod<[], Array<DisputeCase>>,
  'get_equipment_guides' : ActorMethod<[], Array<EquipmentGuide>>,
  'get_forum_posts' : ActorMethod<[], Array<ForumPost>>,
  'get_inventory_items' : ActorMethod<[], Array<InventoryItem>>,
  'get_kyc_records' : ActorMethod<[], Array<KycRecord>>,
  'get_market_price_ticks' : ActorMethod<[], Array<MarketPriceTick>>,
  'get_market_prices' : ActorMethod<[], Array<MarketPrice>>,
  'get_planting_entries' : ActorMethod<[], Array<PlantingEntry>>,
  'get_sales_analytics' : ActorMethod<[], Array<SalesAnalytics>>,
  'get_seasonal_alerts' : ActorMethod<[], Array<SeasonalAlert>>,
  'get_seller_listing' : ActorMethod<[bigint], [] | [SellerListing]>,
  'get_seller_listings' : ActorMethod<[], Array<SellerListing>>,
  'get_team_members' : ActorMethod<[], Array<TeamMember>>,
  'markNotificationRead' : ActorMethod<[bigint], boolean>,
  'sendDirectMessage' : ActorMethod<[CreateDirectMessageInput], DirectMessage>,
  'submitOrder' : ActorMethod<[SubmitOrderInput], Order>,
  'update_kyc_status' : ActorMethod<[bigint, KycVerificationStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];