/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BankAccountInput = IDL.Record({
  'ifsc' : IDL.Text,
  'accountHolderName' : IDL.Text,
  'accountNumber' : IDL.Text,
  'confirmAccountNumber' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const BankVerificationStatus = IDL.Variant({
  'VERIFIED' : IDL.Null,
  'UNVERIFIED' : IDL.Null,
  'PENNY_DROP_PENDING' : IDL.Null,
  'FAILED' : IDL.Null,
});
export const BankAccount = IDL.Record({
  'id' : IDL.Nat,
  'branch' : IDL.Text,
  'userId' : IDL.Nat,
  'ifsc' : IDL.Text,
  'createdAt' : Timestamp,
  'accountHolderName' : IDL.Text,
  'bankName' : IDL.Text,
  'providerToken' : IDL.Text,
  'accountNumberLast4' : IDL.Text,
  'verificationStatus' : BankVerificationStatus,
});
export const KycRejectionReason = IDL.Variant({
  'SELFIE_MISMATCH' : IDL.Null,
  'NAME_MISMATCH' : IDL.Null,
  'EXPIRED_DOCUMENT' : IDL.Null,
  'BLURRY_DOCUMENT' : IDL.Null,
  'FRAUD_SUSPECTED' : IDL.Null,
});
export const KycStatus = IDL.Variant({
  'REJECTED' : IDL.Null,
  'NONE' : IDL.Null,
  'VERIFIED' : IDL.Null,
  'PENDING' : IDL.Null,
  'IN_REVIEW' : IDL.Null,
});
export const KycGateInfo = IDL.Record({
  'rejectionReason' : IDL.Opt(KycRejectionReason),
  'kycStatus' : KycStatus,
  'message' : IDL.Text,
  'canResubmit' : IDL.Bool,
});
export const ApiError = IDL.Variant({
  'InvalidInput' : IDL.Text,
  'ProviderUnavailable' : IDL.Text,
  'KycInProgress' : KycGateInfo,
  'InvalidTransition' : IDL.Record({
    'toStatus' : IDL.Text,
    'fromStatus' : IDL.Text,
    'message' : IDL.Text,
  }),
  'NotFound' : IDL.Text,
  'Unauthorized' : IDL.Text,
  'RateLimited' : IDL.Record({
    'message' : IDL.Text,
    'retryAfterSecs' : IDL.Nat,
  }),
  'KycRequired' : KycGateInfo,
  'Forbidden' : IDL.Text,
  'Conflict' : IDL.Text,
});
export const Result_25 = IDL.Variant({ 'ok' : BankAccount, 'err' : ApiError });
export const Environment = IDL.Variant({
  'Production' : IDL.Null,
  'Development' : IDL.Null,
});
export const AppConfig = IDL.Record({
  'sessionTtlHours' : IDL.Nat,
  'kycAutoApproveThreshold' : IDL.Float64,
  'kycPriorityHighBelow' : IDL.Float64,
  'commissionBps' : IDL.Nat,
  'kycAttemptWindowHours' : IDL.Nat,
  'otpRateLimitWindowSecs' : IDL.Nat,
  'kycMaxAttempts' : IDL.Nat,
  'kycCheckoutThresholdInr' : IDL.Nat,
  'otpExpirySecs' : IDL.Nat,
  'environment' : Environment,
  'kycPriorityMediumBelow' : IDL.Float64,
  'payoutHoldHours' : IDL.Nat,
  'otpRateLimitMax' : IDL.Nat,
});
export const Result_19 = IDL.Variant({ 'ok' : AppConfig, 'err' : ApiError });
export const OrderStatus = IDL.Variant({
  'CANCELLED' : IDL.Null,
  'COMPLETED' : IDL.Null,
  'RESOLVED' : IDL.Null,
  'IN_PROGRESS' : IDL.Null,
  'DISPUTED' : IDL.Null,
  'CONFIRMED' : IDL.Null,
  'PLACED' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'PAID' : IDL.Null,
  'FAILED' : IDL.Null,
  'REFUNDED' : IDL.Null,
  'PENDING' : IDL.Null,
});
export const OrderEvent = IDL.Record({
  'at' : Timestamp,
  'status' : OrderStatus,
  'note' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'listingId' : IDL.Nat,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalAmountInr' : IDL.Nat,
  'buyerId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'sellerId' : IDL.Nat,
  'timeline' : IDL.Vec(OrderEvent),
});
export const OrderView = IDL.Record({
  'order' : Order,
  'listingUnit' : IDL.Text,
  'sellerName' : IDL.Text,
  'listingImageUrl' : IDL.Opt(IDL.Text),
  'listingTitle' : IDL.Text,
  'buyerName' : IDL.Text,
});
export const Result_8 = IDL.Variant({
  'ok' : IDL.Vec(OrderView),
  'err' : ApiError,
});
export const UserRole = IDL.Variant({
  'SELLER' : IDL.Null,
  'BUYER' : IDL.Null,
});
export const KycDocStatus = IDL.Variant({
  'REJECTED' : IDL.Null,
  'VERIFIED' : IDL.Null,
  'PENDING' : IDL.Null,
  'IN_REVIEW' : IDL.Null,
});
export const KycDocType = IDL.Variant({
  'GST' : IDL.Null,
  'PAN' : IDL.Null,
  'AADHAAR' : IDL.Null,
});
export const KycDocument = IDL.Record({
  'id' : IDL.Nat,
  'status' : KycDocStatus,
  'userId' : IDL.Nat,
  'rejectionReason' : IDL.Opt(KycRejectionReason),
  'submittedAt' : Timestamp,
  'selfieUrl' : IDL.Opt(IDL.Text),
  'reviewedAt' : IDL.Opt(Timestamp),
  'reviewedBy' : IDL.Opt(IDL.Nat),
  'confidenceScore' : IDL.Opt(IDL.Float64),
  'isLatest' : IDL.Bool,
  'docType' : KycDocType,
  'fileUrl' : IDL.Text,
  'attemptNumber' : IDL.Nat,
});
export const Priority = IDL.Variant({
  'LOW' : IDL.Null,
  'HIGH' : IDL.Null,
  'MEDIUM' : IDL.Null,
});
export const KycQueueRow = IDL.Record({
  'applicantName' : IDL.Text,
  'applicantPhone' : IDL.Text,
  'applicantRoles' : IDL.Vec(UserRole),
  'document' : KycDocument,
  'priority' : Priority,
});
export const Result_24 = IDL.Variant({
  'ok' : IDL.Vec(KycQueueRow),
  'err' : ApiError,
});
export const ListingStatus = IDL.Variant({
  'REJECTED' : IDL.Null,
  'PENDING_REVIEW' : IDL.Null,
  'SOLD_OUT' : IDL.Null,
  'PUBLISHED' : IDL.Null,
  'ARCHIVED' : IDL.Null,
  'DRAFT' : IDL.Null,
  'PAUSED' : IDL.Null,
});
export const ImageQualityFlag = IDL.Variant({
  'BLURRY' : IDL.Null,
  'LOW_RESOLUTION' : IDL.Null,
});
export const ListingImage = IDL.Record({
  'url' : IDL.Text,
  'qualityFlag' : IDL.Opt(ImageQualityFlag),
  'order' : IDL.Nat,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'moderationNote' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'quantity' : IDL.Nat,
  'sellerId' : IDL.Nat,
  'priceInr' : IDL.Nat,
  'location' : IDL.Text,
  'images' : IDL.Vec(ListingImage),
});
export const ModerationRow = IDL.Record({
  'listing' : Listing,
  'categoryName' : IDL.Text,
  'sellerName' : IDL.Text,
  'sellerKycStatus' : KycStatus,
});
export const Result_23 = IDL.Variant({
  'ok' : IDL.Vec(ModerationRow),
  'err' : ApiError,
});
export const ReportRange = IDL.Record({
  'toNs' : Timestamp,
  'fromNs' : Timestamp,
});
export const Reports = IDL.Record({
  'newUserCount' : IDL.Nat,
  'activeUserCount' : IDL.Nat,
  'gmvInr' : IDL.Nat,
  'toNs' : Timestamp,
  'orderCount' : IDL.Nat,
  'payoutPaidInr' : IDL.Nat,
  'publishedListingCount' : IDL.Nat,
  'fromNs' : Timestamp,
  'totalUserCount' : IDL.Nat,
  'refundedOrderCount' : IDL.Nat,
  'newListingCount' : IDL.Nat,
});
export const Result_22 = IDL.Variant({ 'ok' : Reports, 'err' : ApiError });
export const AdminLoginResult = IDL.Record({
  'token' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'adminId' : IDL.Nat,
});
export const Result_21 = IDL.Variant({
  'ok' : AdminLoginResult,
  'err' : ApiError,
});
export const ModerationAction = IDL.Variant({
  'Approve' : IDL.Null,
  'Reject' : IDL.Text,
  'RequestChanges' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : Listing, 'err' : ApiError });
export const DisputeOutcome = IDL.Variant({
  'RefundBuyer' : IDL.Null,
  'ReleaseToSeller' : IDL.Null,
});
export const Result_2 = IDL.Variant({ 'ok' : OrderView, 'err' : ApiError });
export const KycReviewDecision = IDL.Variant({
  'Approve' : IDL.Null,
  'Reject' : KycRejectionReason,
});
export const Result_20 = IDL.Variant({ 'ok' : KycDocument, 'err' : ApiError });
export const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ApiError });
export const BrowseFilter = IDL.Record({
  'categoryId' : IDL.Opt(IDL.Nat),
  'search' : IDL.Opt(IDL.Text),
});
export const PublicListing = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'categoryName' : IDL.Text,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'sellerKycVerified' : IDL.Bool,
  'description' : IDL.Text,
  'sellerName' : IDL.Text,
  'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'quantity' : IDL.Nat,
  'sellerId' : IDL.Nat,
  'priceInr' : IDL.Nat,
  'location' : IDL.Text,
  'images' : IDL.Vec(ListingImage),
});
export const BusinessType = IDL.Variant({
  'INDIVIDUAL' : IDL.Null,
  'REGISTERED' : IDL.Null,
});
export const OnboardingProfile = IDL.Variant({
  'Buyer' : IDL.Record({ 'name' : IDL.Text, 'deliveryLocation' : IDL.Text }),
  'Seller' : IDL.Record({
    'name' : IDL.Text,
    'businessType' : BusinessType,
    'primaryCategoryId' : IDL.Nat,
  }),
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'kycRejectionReason' : IDL.Opt(KycRejectionReason),
  'businessType' : IDL.Opt(BusinessType),
  'kycStatus' : KycStatus,
  'deliveryLocation' : IDL.Opt(IDL.Text),
  'primaryCategoryId' : IDL.Opt(IDL.Nat),
  'phone' : IDL.Text,
  'roles' : IDL.Vec(UserRole),
});
export const Result_18 = IDL.Variant({ 'ok' : User, 'err' : ApiError });
export const PaymentMethod = IDL.Variant({
  'UPI' : IDL.Null,
  'NETBANKING' : IDL.Null,
  'CARD' : IDL.Null,
});
export const Payment = IDL.Record({
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'idempotencyKey' : IDL.Text,
  'provider' : IDL.Text,
  'listingId' : IDL.Nat,
  'createdAt' : Timestamp,
  'providerPaymentId' : IDL.Text,
  'orderId' : IDL.Opt(IDL.Nat),
  'updatedAt' : Timestamp,
  'buyerId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'amountInr' : IDL.Nat,
});
export const ConfirmCheckoutResult = IDL.Record({
  'order' : IDL.Opt(OrderView),
  'payment' : Payment,
});
export const Result_17 = IDL.Variant({
  'ok' : ConfirmCheckoutResult,
  'err' : ApiError,
});
export const ListingInput = IDL.Record({
  'categoryId' : IDL.Nat,
  'title' : IDL.Text,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'quantity' : IDL.Nat,
  'priceInr' : IDL.Nat,
  'location' : IDL.Text,
  'images' : IDL.Vec(ListingImage),
});
export const TicketCategory = IDL.Variant({
  'KYC' : IDL.Null,
  'ACCOUNT' : IDL.Null,
  'TECHNICAL' : IDL.Null,
  'PAYMENTS' : IDL.Null,
  'ORDER_DISPUTE' : IDL.Null,
});
export const TicketInput = IDL.Record({
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'category' : TicketCategory,
});
export const TicketStatus = IDL.Variant({
  'OPEN' : IDL.Null,
  'RESOLVED' : IDL.Null,
  'IN_PROGRESS' : IDL.Null,
  'CLOSED' : IDL.Null,
});
export const SupportTicket = IDL.Record({
  'id' : IDL.Nat,
  'status' : TicketStatus,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'userId' : IDL.Nat,
  'createdAt' : Timestamp,
  'category' : TicketCategory,
  'priority' : Priority,
  'assignedAdminId' : IDL.Opt(IDL.Nat),
});
export const Result_16 = IDL.Variant({
  'ok' : SupportTicket,
  'err' : ApiError,
});
export const AttributeFieldType = IDL.Variant({
  'SELECT' : IDL.Null,
  'DATE' : IDL.Null,
  'TEXT' : IDL.Null,
  'NUMBER' : IDL.Null,
});
export const AttributeField = IDL.Record({
  'key' : IDL.Text,
  'fieldLabel' : IDL.Text,
  'unit' : IDL.Opt(IDL.Text),
  'required' : IDL.Bool,
  'options' : IDL.Vec(IDL.Text),
  'fieldType' : AttributeFieldType,
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'attributeSchema' : IDL.Vec(AttributeField),
  'name' : IDL.Text,
  'parentId' : IDL.Opt(IDL.Nat),
});
export const KycState = IDL.Record({
  'status' : KycStatus,
  'documents' : IDL.Vec(KycDocument),
  'attemptsUsedInWindow' : IDL.Nat,
  'rejectionReason' : IDL.Opt(KycRejectionReason),
  'canResubmit' : IDL.Bool,
  'maxAttempts' : IDL.Nat,
});
export const Result_3 = IDL.Variant({ 'ok' : KycState, 'err' : ApiError });
export const Result_15 = IDL.Variant({
  'ok' : PublicListing,
  'err' : ApiError,
});
export const MeView = IDL.Record({
  'hasVerifiedBankAccount' : IDL.Bool,
  'unreadNotifications' : IDL.Nat,
  'user' : User,
});
export const Result_14 = IDL.Variant({ 'ok' : MeView, 'err' : ApiError });
export const Result_13 = IDL.Variant({
  'ok' : IDL.Vec(BankAccount),
  'err' : ApiError,
});
export const Result_12 = IDL.Variant({
  'ok' : IDL.Vec(Listing),
  'err' : ApiError,
});
export const NotificationType = IDL.Variant({
  'PAYOUT_UPDATE' : IDL.Null,
  'KYC_UPDATE' : IDL.Null,
  'ORDER_UPDATE' : IDL.Null,
  'SYSTEM' : IDL.Null,
  'LISTING_UPDATE' : IDL.Null,
});
export const NotificationPayload = IDL.Record({
  'listingId' : IDL.Opt(IDL.Nat),
  'payoutId' : IDL.Opt(IDL.Nat),
  'orderId' : IDL.Opt(IDL.Nat),
  'kycDocumentId' : IDL.Opt(IDL.Nat),
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'userId' : IDL.Nat,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'payload' : NotificationPayload,
});
export const Result_11 = IDL.Variant({
  'ok' : IDL.Vec(Notification),
  'err' : ApiError,
});
export const PayoutStatus = IDL.Variant({
  'SCHEDULED' : IDL.Null,
  'PAID' : IDL.Null,
  'FAILED' : IDL.Null,
  'PROCESSING' : IDL.Null,
});
export const Payout = IDL.Record({
  'id' : IDL.Nat,
  'status' : PayoutStatus,
  'bankAccountId' : IDL.Nat,
  'userId' : IDL.Nat,
  'createdAt' : Timestamp,
  'orderId' : IDL.Opt(IDL.Nat),
  'scheduledFor' : Timestamp,
  'amountInr' : IDL.Nat,
  'paidAt' : IDL.Opt(Timestamp),
});
export const Result_10 = IDL.Variant({
  'ok' : IDL.Vec(Payout),
  'err' : ApiError,
});
export const Result_9 = IDL.Variant({
  'ok' : IDL.Vec(SupportTicket),
  'err' : ApiError,
});
export const PublicConfig = IDL.Record({
  'commissionBps' : IDL.Nat,
  'kycAttemptWindowHours' : IDL.Nat,
  'otpRateLimitWindowSecs' : IDL.Nat,
  'kycMaxAttempts' : IDL.Nat,
  'kycCheckoutThresholdInr' : IDL.Nat,
  'otpExpirySecs' : IDL.Nat,
  'environment' : Environment,
  'payoutHoldHours' : IDL.Nat,
  'otpRateLimitMax' : IDL.Nat,
});
export const CheckoutInput = IDL.Record({
  'method' : PaymentMethod,
  'idempotencyKey' : IDL.Text,
  'listingId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const CheckoutIntent = IDL.Record({
  'listingTitle' : IDL.Text,
  'payment' : Payment,
});
export const Result_7 = IDL.Variant({
  'ok' : CheckoutIntent,
  'err' : ApiError,
});
export const Result_6 = IDL.Variant({
  'ok' : IDL.Record({ 'branch' : IDL.Text, 'bankName' : IDL.Text }),
  'err' : ApiError,
});
export const SellerListingAction = IDL.Variant({
  'Restock' : IDL.Nat,
  'Resume' : IDL.Null,
  'Pause' : IDL.Null,
  'Archive' : IDL.Null,
});
export const SendOtpResult = IDL.Record({
  'requestId' : IDL.Text,
  'expiresInSecs' : IDL.Nat,
});
export const Result_4 = IDL.Variant({ 'ok' : SendOtpResult, 'err' : ApiError });
export const KycSubmission = IDL.Record({
  'selfieUrl' : IDL.Opt(IDL.Text),
  'docType' : KycDocType,
  'fileUrl' : IDL.Text,
});
export const VerifyOtpResult = IDL.Record({
  'isNewUser' : IDL.Bool,
  'user' : User,
  'sessionToken' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : VerifyOtpResult, 'err' : ApiError });

export const idlService = IDL.Service({
  'addBankAccount' : IDL.Func([IDL.Text, BankAccountInput], [Result_25], []),
  'adminGetConfig' : IDL.Func([IDL.Text], [Result_19], ['query']),
  'adminGetDisputedOrders' : IDL.Func([IDL.Text], [Result_8], ['query']),
  'adminGetKycQueue' : IDL.Func([IDL.Text], [Result_24], ['query']),
  'adminGetListingQueue' : IDL.Func([IDL.Text], [Result_23], ['query']),
  'adminGetReports' : IDL.Func([IDL.Text, ReportRange], [Result_22], ['query']),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [Result_21], []),
  'adminModerateListing' : IDL.Func(
      [IDL.Text, IDL.Nat, ModerationAction],
      [Result_1],
      [],
    ),
  'adminResolveDispute' : IDL.Func(
      [IDL.Text, IDL.Nat, DisputeOutcome, IDL.Text],
      [Result_2],
      [],
    ),
  'adminReviewKyc' : IDL.Func(
      [IDL.Text, IDL.Nat, KycReviewDecision],
      [Result_20],
      [],
    ),
  'adminRunPayoutCycle' : IDL.Func([IDL.Text], [Result_5], []),
  'adminStartKycReview' : IDL.Func([IDL.Text, IDL.Nat], [Result_20], []),
  'adminUpdateConfig' : IDL.Func([IDL.Text, AppConfig], [Result_19], []),
  'browseListings' : IDL.Func(
      [BrowseFilter],
      [IDL.Vec(PublicListing)],
      ['query'],
    ),
  'completeOnboarding' : IDL.Func(
      [IDL.Text, OnboardingProfile],
      [Result_18],
      [],
    ),
  'confirmCheckout' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [Result_17], []),
  'createListing' : IDL.Func([IDL.Text, ListingInput], [Result_1], []),
  'createSupportTicket' : IDL.Func([IDL.Text, TicketInput], [Result_16], []),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getKycState' : IDL.Func([IDL.Text], [Result_3], ['query']),
  'getListingDetail' : IDL.Func([IDL.Nat], [Result_15], ['query']),
  'getMe' : IDL.Func([IDL.Text], [Result_14], ['query']),
  'getMyBankAccounts' : IDL.Func([IDL.Text], [Result_13], ['query']),
  'getMyListing' : IDL.Func([IDL.Text, IDL.Nat], [Result_1], ['query']),
  'getMyListings' : IDL.Func([IDL.Text], [Result_12], ['query']),
  'getMyNotifications' : IDL.Func([IDL.Text], [Result_11], ['query']),
  'getMyOrders' : IDL.Func([IDL.Text], [Result_8], ['query']),
  'getMyPayouts' : IDL.Func([IDL.Text], [Result_10], []),
  'getMySupportTickets' : IDL.Func([IDL.Text], [Result_9], ['query']),
  'getOrder' : IDL.Func([IDL.Text, IDL.Nat], [Result_2], ['query']),
  'getPublicConfig' : IDL.Func([], [PublicConfig], ['query']),
  'getSellerOrders' : IDL.Func([IDL.Text], [Result_8], ['query']),
  'initiateCheckout' : IDL.Func([IDL.Text, CheckoutInput], [Result_7], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'lookupIfsc' : IDL.Func([IDL.Text], [Result_6], ['query']),
  'manageListing' : IDL.Func(
      [IDL.Text, IDL.Nat, SellerListingAction],
      [Result_1],
      [],
    ),
  'markAllNotificationsRead' : IDL.Func([IDL.Text], [Result_5], []),
  'markNotificationRead' : IDL.Func([IDL.Text, IDL.Nat], [Result_5], []),
  'sendOtp' : IDL.Func([IDL.Text], [Result_4], []),
  'submitKycDocument' : IDL.Func([IDL.Text, KycSubmission], [Result_3], []),
  'submitListingForPublish' : IDL.Func([IDL.Text, IDL.Nat], [Result_1], []),
  'transitionOrderStatus' : IDL.Func(
      [IDL.Text, IDL.Nat, OrderStatus],
      [Result_2],
      [],
    ),
  'updateListing' : IDL.Func([IDL.Text, IDL.Nat, ListingInput], [Result_1], []),
  'verifyOtp' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BankAccountInput = IDL.Record({
    'ifsc' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'accountNumber' : IDL.Text,
    'confirmAccountNumber' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const BankVerificationStatus = IDL.Variant({
    'VERIFIED' : IDL.Null,
    'UNVERIFIED' : IDL.Null,
    'PENNY_DROP_PENDING' : IDL.Null,
    'FAILED' : IDL.Null,
  });
  const BankAccount = IDL.Record({
    'id' : IDL.Nat,
    'branch' : IDL.Text,
    'userId' : IDL.Nat,
    'ifsc' : IDL.Text,
    'createdAt' : Timestamp,
    'accountHolderName' : IDL.Text,
    'bankName' : IDL.Text,
    'providerToken' : IDL.Text,
    'accountNumberLast4' : IDL.Text,
    'verificationStatus' : BankVerificationStatus,
  });
  const KycRejectionReason = IDL.Variant({
    'SELFIE_MISMATCH' : IDL.Null,
    'NAME_MISMATCH' : IDL.Null,
    'EXPIRED_DOCUMENT' : IDL.Null,
    'BLURRY_DOCUMENT' : IDL.Null,
    'FRAUD_SUSPECTED' : IDL.Null,
  });
  const KycStatus = IDL.Variant({
    'REJECTED' : IDL.Null,
    'NONE' : IDL.Null,
    'VERIFIED' : IDL.Null,
    'PENDING' : IDL.Null,
    'IN_REVIEW' : IDL.Null,
  });
  const KycGateInfo = IDL.Record({
    'rejectionReason' : IDL.Opt(KycRejectionReason),
    'kycStatus' : KycStatus,
    'message' : IDL.Text,
    'canResubmit' : IDL.Bool,
  });
  const ApiError = IDL.Variant({
    'InvalidInput' : IDL.Text,
    'ProviderUnavailable' : IDL.Text,
    'KycInProgress' : KycGateInfo,
    'InvalidTransition' : IDL.Record({
      'toStatus' : IDL.Text,
      'fromStatus' : IDL.Text,
      'message' : IDL.Text,
    }),
    'NotFound' : IDL.Text,
    'Unauthorized' : IDL.Text,
    'RateLimited' : IDL.Record({
      'message' : IDL.Text,
      'retryAfterSecs' : IDL.Nat,
    }),
    'KycRequired' : KycGateInfo,
    'Forbidden' : IDL.Text,
    'Conflict' : IDL.Text,
  });
  const Result_25 = IDL.Variant({ 'ok' : BankAccount, 'err' : ApiError });
  const Environment = IDL.Variant({
    'Production' : IDL.Null,
    'Development' : IDL.Null,
  });
  const AppConfig = IDL.Record({
    'sessionTtlHours' : IDL.Nat,
    'kycAutoApproveThreshold' : IDL.Float64,
    'kycPriorityHighBelow' : IDL.Float64,
    'commissionBps' : IDL.Nat,
    'kycAttemptWindowHours' : IDL.Nat,
    'otpRateLimitWindowSecs' : IDL.Nat,
    'kycMaxAttempts' : IDL.Nat,
    'kycCheckoutThresholdInr' : IDL.Nat,
    'otpExpirySecs' : IDL.Nat,
    'environment' : Environment,
    'kycPriorityMediumBelow' : IDL.Float64,
    'payoutHoldHours' : IDL.Nat,
    'otpRateLimitMax' : IDL.Nat,
  });
  const Result_19 = IDL.Variant({ 'ok' : AppConfig, 'err' : ApiError });
  const OrderStatus = IDL.Variant({
    'CANCELLED' : IDL.Null,
    'COMPLETED' : IDL.Null,
    'RESOLVED' : IDL.Null,
    'IN_PROGRESS' : IDL.Null,
    'DISPUTED' : IDL.Null,
    'CONFIRMED' : IDL.Null,
    'PLACED' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'PAID' : IDL.Null,
    'FAILED' : IDL.Null,
    'REFUNDED' : IDL.Null,
    'PENDING' : IDL.Null,
  });
  const OrderEvent = IDL.Record({
    'at' : Timestamp,
    'status' : OrderStatus,
    'note' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'paymentStatus' : PaymentStatus,
    'listingId' : IDL.Nat,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'totalAmountInr' : IDL.Nat,
    'buyerId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'sellerId' : IDL.Nat,
    'timeline' : IDL.Vec(OrderEvent),
  });
  const OrderView = IDL.Record({
    'order' : Order,
    'listingUnit' : IDL.Text,
    'sellerName' : IDL.Text,
    'listingImageUrl' : IDL.Opt(IDL.Text),
    'listingTitle' : IDL.Text,
    'buyerName' : IDL.Text,
  });
  const Result_8 = IDL.Variant({ 'ok' : IDL.Vec(OrderView), 'err' : ApiError });
  const UserRole = IDL.Variant({ 'SELLER' : IDL.Null, 'BUYER' : IDL.Null });
  const KycDocStatus = IDL.Variant({
    'REJECTED' : IDL.Null,
    'VERIFIED' : IDL.Null,
    'PENDING' : IDL.Null,
    'IN_REVIEW' : IDL.Null,
  });
  const KycDocType = IDL.Variant({
    'GST' : IDL.Null,
    'PAN' : IDL.Null,
    'AADHAAR' : IDL.Null,
  });
  const KycDocument = IDL.Record({
    'id' : IDL.Nat,
    'status' : KycDocStatus,
    'userId' : IDL.Nat,
    'rejectionReason' : IDL.Opt(KycRejectionReason),
    'submittedAt' : Timestamp,
    'selfieUrl' : IDL.Opt(IDL.Text),
    'reviewedAt' : IDL.Opt(Timestamp),
    'reviewedBy' : IDL.Opt(IDL.Nat),
    'confidenceScore' : IDL.Opt(IDL.Float64),
    'isLatest' : IDL.Bool,
    'docType' : KycDocType,
    'fileUrl' : IDL.Text,
    'attemptNumber' : IDL.Nat,
  });
  const Priority = IDL.Variant({
    'LOW' : IDL.Null,
    'HIGH' : IDL.Null,
    'MEDIUM' : IDL.Null,
  });
  const KycQueueRow = IDL.Record({
    'applicantName' : IDL.Text,
    'applicantPhone' : IDL.Text,
    'applicantRoles' : IDL.Vec(UserRole),
    'document' : KycDocument,
    'priority' : Priority,
  });
  const Result_24 = IDL.Variant({
    'ok' : IDL.Vec(KycQueueRow),
    'err' : ApiError,
  });
  const ListingStatus = IDL.Variant({
    'REJECTED' : IDL.Null,
    'PENDING_REVIEW' : IDL.Null,
    'SOLD_OUT' : IDL.Null,
    'PUBLISHED' : IDL.Null,
    'ARCHIVED' : IDL.Null,
    'DRAFT' : IDL.Null,
    'PAUSED' : IDL.Null,
  });
  const ImageQualityFlag = IDL.Variant({
    'BLURRY' : IDL.Null,
    'LOW_RESOLUTION' : IDL.Null,
  });
  const ListingImage = IDL.Record({
    'url' : IDL.Text,
    'qualityFlag' : IDL.Opt(ImageQualityFlag),
    'order' : IDL.Nat,
  });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'moderationNote' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'quantity' : IDL.Nat,
    'sellerId' : IDL.Nat,
    'priceInr' : IDL.Nat,
    'location' : IDL.Text,
    'images' : IDL.Vec(ListingImage),
  });
  const ModerationRow = IDL.Record({
    'listing' : Listing,
    'categoryName' : IDL.Text,
    'sellerName' : IDL.Text,
    'sellerKycStatus' : KycStatus,
  });
  const Result_23 = IDL.Variant({
    'ok' : IDL.Vec(ModerationRow),
    'err' : ApiError,
  });
  const ReportRange = IDL.Record({ 'toNs' : Timestamp, 'fromNs' : Timestamp });
  const Reports = IDL.Record({
    'newUserCount' : IDL.Nat,
    'activeUserCount' : IDL.Nat,
    'gmvInr' : IDL.Nat,
    'toNs' : Timestamp,
    'orderCount' : IDL.Nat,
    'payoutPaidInr' : IDL.Nat,
    'publishedListingCount' : IDL.Nat,
    'fromNs' : Timestamp,
    'totalUserCount' : IDL.Nat,
    'refundedOrderCount' : IDL.Nat,
    'newListingCount' : IDL.Nat,
  });
  const Result_22 = IDL.Variant({ 'ok' : Reports, 'err' : ApiError });
  const AdminLoginResult = IDL.Record({
    'token' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'adminId' : IDL.Nat,
  });
  const Result_21 = IDL.Variant({ 'ok' : AdminLoginResult, 'err' : ApiError });
  const ModerationAction = IDL.Variant({
    'Approve' : IDL.Null,
    'Reject' : IDL.Text,
    'RequestChanges' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : Listing, 'err' : ApiError });
  const DisputeOutcome = IDL.Variant({
    'RefundBuyer' : IDL.Null,
    'ReleaseToSeller' : IDL.Null,
  });
  const Result_2 = IDL.Variant({ 'ok' : OrderView, 'err' : ApiError });
  const KycReviewDecision = IDL.Variant({
    'Approve' : IDL.Null,
    'Reject' : KycRejectionReason,
  });
  const Result_20 = IDL.Variant({ 'ok' : KycDocument, 'err' : ApiError });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ApiError });
  const BrowseFilter = IDL.Record({
    'categoryId' : IDL.Opt(IDL.Nat),
    'search' : IDL.Opt(IDL.Text),
  });
  const PublicListing = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'categoryName' : IDL.Text,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'sellerKycVerified' : IDL.Bool,
    'description' : IDL.Text,
    'sellerName' : IDL.Text,
    'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'quantity' : IDL.Nat,
    'sellerId' : IDL.Nat,
    'priceInr' : IDL.Nat,
    'location' : IDL.Text,
    'images' : IDL.Vec(ListingImage),
  });
  const BusinessType = IDL.Variant({
    'INDIVIDUAL' : IDL.Null,
    'REGISTERED' : IDL.Null,
  });
  const OnboardingProfile = IDL.Variant({
    'Buyer' : IDL.Record({ 'name' : IDL.Text, 'deliveryLocation' : IDL.Text }),
    'Seller' : IDL.Record({
      'name' : IDL.Text,
      'businessType' : BusinessType,
      'primaryCategoryId' : IDL.Nat,
    }),
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'kycRejectionReason' : IDL.Opt(KycRejectionReason),
    'businessType' : IDL.Opt(BusinessType),
    'kycStatus' : KycStatus,
    'deliveryLocation' : IDL.Opt(IDL.Text),
    'primaryCategoryId' : IDL.Opt(IDL.Nat),
    'phone' : IDL.Text,
    'roles' : IDL.Vec(UserRole),
  });
  const Result_18 = IDL.Variant({ 'ok' : User, 'err' : ApiError });
  const PaymentMethod = IDL.Variant({
    'UPI' : IDL.Null,
    'NETBANKING' : IDL.Null,
    'CARD' : IDL.Null,
  });
  const Payment = IDL.Record({
    'status' : PaymentStatus,
    'method' : PaymentMethod,
    'idempotencyKey' : IDL.Text,
    'provider' : IDL.Text,
    'listingId' : IDL.Nat,
    'createdAt' : Timestamp,
    'providerPaymentId' : IDL.Text,
    'orderId' : IDL.Opt(IDL.Nat),
    'updatedAt' : Timestamp,
    'buyerId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'amountInr' : IDL.Nat,
  });
  const ConfirmCheckoutResult = IDL.Record({
    'order' : IDL.Opt(OrderView),
    'payment' : Payment,
  });
  const Result_17 = IDL.Variant({
    'ok' : ConfirmCheckoutResult,
    'err' : ApiError,
  });
  const ListingInput = IDL.Record({
    'categoryId' : IDL.Nat,
    'title' : IDL.Text,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'quantity' : IDL.Nat,
    'priceInr' : IDL.Nat,
    'location' : IDL.Text,
    'images' : IDL.Vec(ListingImage),
  });
  const TicketCategory = IDL.Variant({
    'KYC' : IDL.Null,
    'ACCOUNT' : IDL.Null,
    'TECHNICAL' : IDL.Null,
    'PAYMENTS' : IDL.Null,
    'ORDER_DISPUTE' : IDL.Null,
  });
  const TicketInput = IDL.Record({
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'category' : TicketCategory,
  });
  const TicketStatus = IDL.Variant({
    'OPEN' : IDL.Null,
    'RESOLVED' : IDL.Null,
    'IN_PROGRESS' : IDL.Null,
    'CLOSED' : IDL.Null,
  });
  const SupportTicket = IDL.Record({
    'id' : IDL.Nat,
    'status' : TicketStatus,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'userId' : IDL.Nat,
    'createdAt' : Timestamp,
    'category' : TicketCategory,
    'priority' : Priority,
    'assignedAdminId' : IDL.Opt(IDL.Nat),
  });
  const Result_16 = IDL.Variant({ 'ok' : SupportTicket, 'err' : ApiError });
  const AttributeFieldType = IDL.Variant({
    'SELECT' : IDL.Null,
    'DATE' : IDL.Null,
    'TEXT' : IDL.Null,
    'NUMBER' : IDL.Null,
  });
  const AttributeField = IDL.Record({
    'key' : IDL.Text,
    'fieldLabel' : IDL.Text,
    'unit' : IDL.Opt(IDL.Text),
    'required' : IDL.Bool,
    'options' : IDL.Vec(IDL.Text),
    'fieldType' : AttributeFieldType,
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'attributeSchema' : IDL.Vec(AttributeField),
    'name' : IDL.Text,
    'parentId' : IDL.Opt(IDL.Nat),
  });
  const KycState = IDL.Record({
    'status' : KycStatus,
    'documents' : IDL.Vec(KycDocument),
    'attemptsUsedInWindow' : IDL.Nat,
    'rejectionReason' : IDL.Opt(KycRejectionReason),
    'canResubmit' : IDL.Bool,
    'maxAttempts' : IDL.Nat,
  });
  const Result_3 = IDL.Variant({ 'ok' : KycState, 'err' : ApiError });
  const Result_15 = IDL.Variant({ 'ok' : PublicListing, 'err' : ApiError });
  const MeView = IDL.Record({
    'hasVerifiedBankAccount' : IDL.Bool,
    'unreadNotifications' : IDL.Nat,
    'user' : User,
  });
  const Result_14 = IDL.Variant({ 'ok' : MeView, 'err' : ApiError });
  const Result_13 = IDL.Variant({
    'ok' : IDL.Vec(BankAccount),
    'err' : ApiError,
  });
  const Result_12 = IDL.Variant({ 'ok' : IDL.Vec(Listing), 'err' : ApiError });
  const NotificationType = IDL.Variant({
    'PAYOUT_UPDATE' : IDL.Null,
    'KYC_UPDATE' : IDL.Null,
    'ORDER_UPDATE' : IDL.Null,
    'SYSTEM' : IDL.Null,
    'LISTING_UPDATE' : IDL.Null,
  });
  const NotificationPayload = IDL.Record({
    'listingId' : IDL.Opt(IDL.Nat),
    'payoutId' : IDL.Opt(IDL.Nat),
    'orderId' : IDL.Opt(IDL.Nat),
    'kycDocumentId' : IDL.Opt(IDL.Nat),
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'userId' : IDL.Nat,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'payload' : NotificationPayload,
  });
  const Result_11 = IDL.Variant({
    'ok' : IDL.Vec(Notification),
    'err' : ApiError,
  });
  const PayoutStatus = IDL.Variant({
    'SCHEDULED' : IDL.Null,
    'PAID' : IDL.Null,
    'FAILED' : IDL.Null,
    'PROCESSING' : IDL.Null,
  });
  const Payout = IDL.Record({
    'id' : IDL.Nat,
    'status' : PayoutStatus,
    'bankAccountId' : IDL.Nat,
    'userId' : IDL.Nat,
    'createdAt' : Timestamp,
    'orderId' : IDL.Opt(IDL.Nat),
    'scheduledFor' : Timestamp,
    'amountInr' : IDL.Nat,
    'paidAt' : IDL.Opt(Timestamp),
  });
  const Result_10 = IDL.Variant({ 'ok' : IDL.Vec(Payout), 'err' : ApiError });
  const Result_9 = IDL.Variant({
    'ok' : IDL.Vec(SupportTicket),
    'err' : ApiError,
  });
  const PublicConfig = IDL.Record({
    'commissionBps' : IDL.Nat,
    'kycAttemptWindowHours' : IDL.Nat,
    'otpRateLimitWindowSecs' : IDL.Nat,
    'kycMaxAttempts' : IDL.Nat,
    'kycCheckoutThresholdInr' : IDL.Nat,
    'otpExpirySecs' : IDL.Nat,
    'environment' : Environment,
    'payoutHoldHours' : IDL.Nat,
    'otpRateLimitMax' : IDL.Nat,
  });
  const CheckoutInput = IDL.Record({
    'method' : PaymentMethod,
    'idempotencyKey' : IDL.Text,
    'listingId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const CheckoutIntent = IDL.Record({
    'listingTitle' : IDL.Text,
    'payment' : Payment,
  });
  const Result_7 = IDL.Variant({ 'ok' : CheckoutIntent, 'err' : ApiError });
  const Result_6 = IDL.Variant({
    'ok' : IDL.Record({ 'branch' : IDL.Text, 'bankName' : IDL.Text }),
    'err' : ApiError,
  });
  const SellerListingAction = IDL.Variant({
    'Restock' : IDL.Nat,
    'Resume' : IDL.Null,
    'Pause' : IDL.Null,
    'Archive' : IDL.Null,
  });
  const SendOtpResult = IDL.Record({
    'requestId' : IDL.Text,
    'expiresInSecs' : IDL.Nat,
  });
  const Result_4 = IDL.Variant({ 'ok' : SendOtpResult, 'err' : ApiError });
  const KycSubmission = IDL.Record({
    'selfieUrl' : IDL.Opt(IDL.Text),
    'docType' : KycDocType,
    'fileUrl' : IDL.Text,
  });
  const VerifyOtpResult = IDL.Record({
    'isNewUser' : IDL.Bool,
    'user' : User,
    'sessionToken' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : VerifyOtpResult, 'err' : ApiError });
  
  return IDL.Service({
    'addBankAccount' : IDL.Func([IDL.Text, BankAccountInput], [Result_25], []),
    'adminGetConfig' : IDL.Func([IDL.Text], [Result_19], ['query']),
    'adminGetDisputedOrders' : IDL.Func([IDL.Text], [Result_8], ['query']),
    'adminGetKycQueue' : IDL.Func([IDL.Text], [Result_24], ['query']),
    'adminGetListingQueue' : IDL.Func([IDL.Text], [Result_23], ['query']),
    'adminGetReports' : IDL.Func(
        [IDL.Text, ReportRange],
        [Result_22],
        ['query'],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [Result_21], []),
    'adminModerateListing' : IDL.Func(
        [IDL.Text, IDL.Nat, ModerationAction],
        [Result_1],
        [],
      ),
    'adminResolveDispute' : IDL.Func(
        [IDL.Text, IDL.Nat, DisputeOutcome, IDL.Text],
        [Result_2],
        [],
      ),
    'adminReviewKyc' : IDL.Func(
        [IDL.Text, IDL.Nat, KycReviewDecision],
        [Result_20],
        [],
      ),
    'adminRunPayoutCycle' : IDL.Func([IDL.Text], [Result_5], []),
    'adminStartKycReview' : IDL.Func([IDL.Text, IDL.Nat], [Result_20], []),
    'adminUpdateConfig' : IDL.Func([IDL.Text, AppConfig], [Result_19], []),
    'browseListings' : IDL.Func(
        [BrowseFilter],
        [IDL.Vec(PublicListing)],
        ['query'],
      ),
    'completeOnboarding' : IDL.Func(
        [IDL.Text, OnboardingProfile],
        [Result_18],
        [],
      ),
    'confirmCheckout' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [Result_17],
        [],
      ),
    'createListing' : IDL.Func([IDL.Text, ListingInput], [Result_1], []),
    'createSupportTicket' : IDL.Func([IDL.Text, TicketInput], [Result_16], []),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getKycState' : IDL.Func([IDL.Text], [Result_3], ['query']),
    'getListingDetail' : IDL.Func([IDL.Nat], [Result_15], ['query']),
    'getMe' : IDL.Func([IDL.Text], [Result_14], ['query']),
    'getMyBankAccounts' : IDL.Func([IDL.Text], [Result_13], ['query']),
    'getMyListing' : IDL.Func([IDL.Text, IDL.Nat], [Result_1], ['query']),
    'getMyListings' : IDL.Func([IDL.Text], [Result_12], ['query']),
    'getMyNotifications' : IDL.Func([IDL.Text], [Result_11], ['query']),
    'getMyOrders' : IDL.Func([IDL.Text], [Result_8], ['query']),
    'getMyPayouts' : IDL.Func([IDL.Text], [Result_10], []),
    'getMySupportTickets' : IDL.Func([IDL.Text], [Result_9], ['query']),
    'getOrder' : IDL.Func([IDL.Text, IDL.Nat], [Result_2], ['query']),
    'getPublicConfig' : IDL.Func([], [PublicConfig], ['query']),
    'getSellerOrders' : IDL.Func([IDL.Text], [Result_8], ['query']),
    'initiateCheckout' : IDL.Func([IDL.Text, CheckoutInput], [Result_7], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'lookupIfsc' : IDL.Func([IDL.Text], [Result_6], ['query']),
    'manageListing' : IDL.Func(
        [IDL.Text, IDL.Nat, SellerListingAction],
        [Result_1],
        [],
      ),
    'markAllNotificationsRead' : IDL.Func([IDL.Text], [Result_5], []),
    'markNotificationRead' : IDL.Func([IDL.Text, IDL.Nat], [Result_5], []),
    'sendOtp' : IDL.Func([IDL.Text], [Result_4], []),
    'submitKycDocument' : IDL.Func([IDL.Text, KycSubmission], [Result_3], []),
    'submitListingForPublish' : IDL.Func([IDL.Text, IDL.Nat], [Result_1], []),
    'transitionOrderStatus' : IDL.Func(
        [IDL.Text, IDL.Nat, OrderStatus],
        [Result_2],
        [],
      ),
    'updateListing' : IDL.Func(
        [IDL.Text, IDL.Nat, ListingInput],
        [Result_1],
        [],
      ),
    'verifyOtp' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };