/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminLoginResult {
  'token' : string,
  'name' : string,
  'email' : string,
  'adminId' : bigint,
}
export type ApiError = { 'InvalidInput' : string } |
  { 'ProviderUnavailable' : string } |
  { 'KycInProgress' : KycGateInfo } |
  {
    'InvalidTransition' : {
      'toStatus' : string,
      'fromStatus' : string,
      'message' : string,
    }
  } |
  { 'NotFound' : string } |
  { 'Unauthorized' : string } |
  { 'RateLimited' : { 'message' : string, 'retryAfterSecs' : bigint } } |
  { 'KycRequired' : KycGateInfo } |
  { 'Forbidden' : string } |
  { 'Conflict' : string };
export interface AppConfig {
  'sessionTtlHours' : bigint,
  'kycAutoApproveThreshold' : number,
  'kycPriorityHighBelow' : number,
  'commissionBps' : bigint,
  'kycAttemptWindowHours' : bigint,
  'otpRateLimitWindowSecs' : bigint,
  'kycMaxAttempts' : bigint,
  'kycCheckoutThresholdInr' : bigint,
  'otpExpirySecs' : bigint,
  'environment' : Environment,
  'kycPriorityMediumBelow' : number,
  'payoutHoldHours' : bigint,
  'otpRateLimitMax' : bigint,
}
export interface AttributeField {
  'key' : string,
  'fieldLabel' : string,
  'unit' : [] | [string],
  'required' : boolean,
  'options' : Array<string>,
  'fieldType' : AttributeFieldType,
}
export type AttributeFieldType = { 'SELECT' : null } |
  { 'DATE' : null } |
  { 'TEXT' : null } |
  { 'NUMBER' : null };
export interface BankAccount {
  'id' : bigint,
  'branch' : string,
  'userId' : bigint,
  'ifsc' : string,
  'createdAt' : Timestamp,
  'accountHolderName' : string,
  'bankName' : string,
  'providerToken' : string,
  'accountNumberLast4' : string,
  'verificationStatus' : BankVerificationStatus,
}
export interface BankAccountInput {
  'ifsc' : string,
  'accountHolderName' : string,
  'accountNumber' : string,
  'confirmAccountNumber' : string,
}
export type BankVerificationStatus = { 'VERIFIED' : null } |
  { 'UNVERIFIED' : null } |
  { 'PENNY_DROP_PENDING' : null } |
  { 'FAILED' : null };
export interface BrowseFilter {
  'categoryId' : [] | [bigint],
  'search' : [] | [string],
}
export type BusinessType = { 'INDIVIDUAL' : null } |
  { 'REGISTERED' : null };
export interface Category {
  'id' : bigint,
  'attributeSchema' : Array<AttributeField>,
  'name' : string,
  'parentId' : [] | [bigint],
}
export interface CheckoutInput {
  'method' : PaymentMethod,
  'idempotencyKey' : string,
  'listingId' : bigint,
  'quantity' : bigint,
}
export interface CheckoutIntent { 'listingTitle' : string, 'payment' : Payment }
export interface ConfirmCheckoutResult {
  'order' : [] | [OrderView],
  'payment' : Payment,
}
export type DisputeOutcome = { 'RefundBuyer' : null } |
  { 'ReleaseToSeller' : null };
export type Environment = { 'Production' : null } |
  { 'Development' : null };
export type ImageQualityFlag = { 'BLURRY' : null } |
  { 'LOW_RESOLUTION' : null };
export type KycDocStatus = { 'REJECTED' : null } |
  { 'VERIFIED' : null } |
  { 'PENDING' : null } |
  { 'IN_REVIEW' : null };
export type KycDocType = { 'GST' : null } |
  { 'PAN' : null } |
  { 'AADHAAR' : null };
export interface KycDocument {
  'id' : bigint,
  'status' : KycDocStatus,
  'userId' : bigint,
  'rejectionReason' : [] | [KycRejectionReason],
  'submittedAt' : Timestamp,
  'selfieUrl' : [] | [string],
  'reviewedAt' : [] | [Timestamp],
  'reviewedBy' : [] | [bigint],
  'confidenceScore' : [] | [number],
  'isLatest' : boolean,
  'docType' : KycDocType,
  'fileUrl' : string,
  'attemptNumber' : bigint,
}
export interface KycGateInfo {
  'rejectionReason' : [] | [KycRejectionReason],
  'kycStatus' : KycStatus,
  'message' : string,
  'canResubmit' : boolean,
}
export interface KycQueueRow {
  'applicantName' : string,
  'applicantPhone' : string,
  'applicantRoles' : Array<UserRole>,
  'document' : KycDocument,
  'priority' : Priority,
}
export type KycRejectionReason = { 'SELFIE_MISMATCH' : null } |
  { 'NAME_MISMATCH' : null } |
  { 'EXPIRED_DOCUMENT' : null } |
  { 'BLURRY_DOCUMENT' : null } |
  { 'FRAUD_SUSPECTED' : null };
export type KycReviewDecision = { 'Approve' : null } |
  { 'Reject' : KycRejectionReason };
export interface KycState {
  'status' : KycStatus,
  'documents' : Array<KycDocument>,
  'attemptsUsedInWindow' : bigint,
  'rejectionReason' : [] | [KycRejectionReason],
  'canResubmit' : boolean,
  'maxAttempts' : bigint,
}
export type KycStatus = { 'REJECTED' : null } |
  { 'NONE' : null } |
  { 'VERIFIED' : null } |
  { 'PENDING' : null } |
  { 'IN_REVIEW' : null };
export interface KycSubmission {
  'selfieUrl' : [] | [string],
  'docType' : KycDocType,
  'fileUrl' : string,
}
export interface Listing {
  'id' : bigint,
  'categoryId' : bigint,
  'status' : ListingStatus,
  'title' : string,
  'moderationNote' : [] | [string],
  'createdAt' : Timestamp,
  'unit' : string,
  'description' : string,
  'updatedAt' : Timestamp,
  'attributes' : Array<[string, string]>,
  'quantity' : bigint,
  'sellerId' : bigint,
  'priceInr' : bigint,
  'location' : string,
  'images' : Array<ListingImage>,
}
export interface ListingImage {
  'url' : string,
  'qualityFlag' : [] | [ImageQualityFlag],
  'order' : bigint,
}
export interface ListingInput {
  'categoryId' : bigint,
  'title' : string,
  'unit' : string,
  'description' : string,
  'attributes' : Array<[string, string]>,
  'quantity' : bigint,
  'priceInr' : bigint,
  'location' : string,
  'images' : Array<ListingImage>,
}
export type ListingStatus = { 'REJECTED' : null } |
  { 'PENDING_REVIEW' : null } |
  { 'SOLD_OUT' : null } |
  { 'PUBLISHED' : null } |
  { 'ARCHIVED' : null } |
  { 'DRAFT' : null } |
  { 'PAUSED' : null };
export interface MeView {
  'hasVerifiedBankAccount' : boolean,
  'unreadNotifications' : bigint,
  'user' : User,
}
export type ModerationAction = { 'Approve' : null } |
  { 'Reject' : string } |
  { 'RequestChanges' : string };
export interface ModerationRow {
  'listing' : Listing,
  'categoryName' : string,
  'sellerName' : string,
  'sellerKycStatus' : KycStatus,
}
export interface Notification {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'userId' : bigint,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : boolean,
  'payload' : NotificationPayload,
}
export interface NotificationPayload {
  'listingId' : [] | [bigint],
  'payoutId' : [] | [bigint],
  'orderId' : [] | [bigint],
  'kycDocumentId' : [] | [bigint],
}
export type NotificationType = { 'PAYOUT_UPDATE' : null } |
  { 'KYC_UPDATE' : null } |
  { 'ORDER_UPDATE' : null } |
  { 'SYSTEM' : null } |
  { 'LISTING_UPDATE' : null };
export type OnboardingProfile = {
    'Buyer' : { 'name' : string, 'deliveryLocation' : string }
  } |
  {
    'Seller' : {
      'name' : string,
      'businessType' : BusinessType,
      'primaryCategoryId' : bigint,
    }
  };
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'listingId' : bigint,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalAmountInr' : bigint,
  'buyerId' : bigint,
  'quantity' : bigint,
  'sellerId' : bigint,
  'timeline' : Array<OrderEvent>,
}
export interface OrderEvent {
  'at' : Timestamp,
  'status' : OrderStatus,
  'note' : string,
}
export type OrderStatus = { 'CANCELLED' : null } |
  { 'COMPLETED' : null } |
  { 'RESOLVED' : null } |
  { 'IN_PROGRESS' : null } |
  { 'DISPUTED' : null } |
  { 'CONFIRMED' : null } |
  { 'PLACED' : null };
export interface OrderView {
  'order' : Order,
  'listingUnit' : string,
  'sellerName' : string,
  'listingImageUrl' : [] | [string],
  'listingTitle' : string,
  'buyerName' : string,
}
export interface Payment {
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'idempotencyKey' : string,
  'provider' : string,
  'listingId' : bigint,
  'createdAt' : Timestamp,
  'providerPaymentId' : string,
  'orderId' : [] | [bigint],
  'updatedAt' : Timestamp,
  'buyerId' : bigint,
  'quantity' : bigint,
  'amountInr' : bigint,
}
export type PaymentMethod = { 'UPI' : null } |
  { 'NETBANKING' : null } |
  { 'CARD' : null };
export type PaymentStatus = { 'PAID' : null } |
  { 'FAILED' : null } |
  { 'REFUNDED' : null } |
  { 'PENDING' : null };
export interface Payout {
  'id' : bigint,
  'status' : PayoutStatus,
  'bankAccountId' : bigint,
  'userId' : bigint,
  'createdAt' : Timestamp,
  'orderId' : [] | [bigint],
  'scheduledFor' : Timestamp,
  'amountInr' : bigint,
  'paidAt' : [] | [Timestamp],
}
export type PayoutStatus = { 'SCHEDULED' : null } |
  { 'PAID' : null } |
  { 'FAILED' : null } |
  { 'PROCESSING' : null };
export type Priority = { 'LOW' : null } |
  { 'HIGH' : null } |
  { 'MEDIUM' : null };
export interface PublicConfig {
  'commissionBps' : bigint,
  'kycAttemptWindowHours' : bigint,
  'otpRateLimitWindowSecs' : bigint,
  'kycMaxAttempts' : bigint,
  'kycCheckoutThresholdInr' : bigint,
  'otpExpirySecs' : bigint,
  'environment' : Environment,
  'payoutHoldHours' : bigint,
  'otpRateLimitMax' : bigint,
}
export interface PublicListing {
  'id' : bigint,
  'categoryId' : bigint,
  'status' : ListingStatus,
  'title' : string,
  'categoryName' : string,
  'createdAt' : Timestamp,
  'unit' : string,
  'sellerKycVerified' : boolean,
  'description' : string,
  'sellerName' : string,
  'attributes' : Array<[string, string]>,
  'quantity' : bigint,
  'sellerId' : bigint,
  'priceInr' : bigint,
  'location' : string,
  'images' : Array<ListingImage>,
}
export interface ReportRange { 'toNs' : Timestamp, 'fromNs' : Timestamp }
export interface Reports {
  'newUserCount' : bigint,
  'activeUserCount' : bigint,
  'gmvInr' : bigint,
  'toNs' : Timestamp,
  'orderCount' : bigint,
  'payoutPaidInr' : bigint,
  'publishedListingCount' : bigint,
  'fromNs' : Timestamp,
  'totalUserCount' : bigint,
  'refundedOrderCount' : bigint,
  'newListingCount' : bigint,
}
export type Result = { 'ok' : VerifyOtpResult } |
  { 'err' : ApiError };
export type Result_1 = { 'ok' : Listing } |
  { 'err' : ApiError };
export type Result_10 = { 'ok' : Array<Payout> } |
  { 'err' : ApiError };
export type Result_11 = { 'ok' : Array<Notification> } |
  { 'err' : ApiError };
export type Result_12 = { 'ok' : Array<Listing> } |
  { 'err' : ApiError };
export type Result_13 = { 'ok' : Array<BankAccount> } |
  { 'err' : ApiError };
export type Result_14 = { 'ok' : MeView } |
  { 'err' : ApiError };
export type Result_15 = { 'ok' : PublicListing } |
  { 'err' : ApiError };
export type Result_16 = { 'ok' : SupportTicket } |
  { 'err' : ApiError };
export type Result_17 = { 'ok' : ConfirmCheckoutResult } |
  { 'err' : ApiError };
export type Result_18 = { 'ok' : User } |
  { 'err' : ApiError };
export type Result_19 = { 'ok' : AppConfig } |
  { 'err' : ApiError };
export type Result_2 = { 'ok' : OrderView } |
  { 'err' : ApiError };
export type Result_20 = { 'ok' : KycDocument } |
  { 'err' : ApiError };
export type Result_21 = { 'ok' : AdminLoginResult } |
  { 'err' : ApiError };
export type Result_22 = { 'ok' : Reports } |
  { 'err' : ApiError };
export type Result_23 = { 'ok' : Array<ModerationRow> } |
  { 'err' : ApiError };
export type Result_24 = { 'ok' : Array<KycQueueRow> } |
  { 'err' : ApiError };
export type Result_25 = { 'ok' : BankAccount } |
  { 'err' : ApiError };
export type Result_3 = { 'ok' : KycState } |
  { 'err' : ApiError };
export type Result_4 = { 'ok' : SendOtpResult } |
  { 'err' : ApiError };
export type Result_5 = { 'ok' : null } |
  { 'err' : ApiError };
export type Result_6 = { 'ok' : { 'branch' : string, 'bankName' : string } } |
  { 'err' : ApiError };
export type Result_7 = { 'ok' : CheckoutIntent } |
  { 'err' : ApiError };
export type Result_8 = { 'ok' : Array<OrderView> } |
  { 'err' : ApiError };
export type Result_9 = { 'ok' : Array<SupportTicket> } |
  { 'err' : ApiError };
export type SellerListingAction = { 'Restock' : bigint } |
  { 'Resume' : null } |
  { 'Pause' : null } |
  { 'Archive' : null };
export interface SendOtpResult {
  'requestId' : string,
  'expiresInSecs' : bigint,
}
export interface SupportTicket {
  'id' : bigint,
  'status' : TicketStatus,
  'subject' : string,
  'body' : string,
  'userId' : bigint,
  'createdAt' : Timestamp,
  'category' : TicketCategory,
  'priority' : Priority,
  'assignedAdminId' : [] | [bigint],
}
export type TicketCategory = { 'KYC' : null } |
  { 'ACCOUNT' : null } |
  { 'TECHNICAL' : null } |
  { 'PAYMENTS' : null } |
  { 'ORDER_DISPUTE' : null };
export interface TicketInput {
  'subject' : string,
  'body' : string,
  'category' : TicketCategory,
}
export type TicketStatus = { 'OPEN' : null } |
  { 'RESOLVED' : null } |
  { 'IN_PROGRESS' : null } |
  { 'CLOSED' : null };
export type Timestamp = bigint;
export interface User {
  'id' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'kycRejectionReason' : [] | [KycRejectionReason],
  'businessType' : [] | [BusinessType],
  'kycStatus' : KycStatus,
  'deliveryLocation' : [] | [string],
  'primaryCategoryId' : [] | [bigint],
  'phone' : string,
  'roles' : Array<UserRole>,
}
export type UserRole = { 'SELLER' : null } |
  { 'BUYER' : null };
export interface VerifyOtpResult {
  'isNewUser' : boolean,
  'user' : User,
  'sessionToken' : string,
}
export interface _SERVICE {
  'addBankAccount' : ActorMethod<[string, BankAccountInput], Result_25>,
  'adminGetConfig' : ActorMethod<[string], Result_19>,
  'adminGetDisputedOrders' : ActorMethod<[string], Result_8>,
  'adminGetKycQueue' : ActorMethod<[string], Result_24>,
  'adminGetListingQueue' : ActorMethod<[string], Result_23>,
  'adminGetReports' : ActorMethod<[string, ReportRange], Result_22>,
  'adminLogin' : ActorMethod<[string, string], Result_21>,
  'adminModerateListing' : ActorMethod<
    [string, bigint, ModerationAction],
    Result_1
  >,
  'adminResolveDispute' : ActorMethod<
    [string, bigint, DisputeOutcome, string],
    Result_2
  >,
  'adminReviewKyc' : ActorMethod<
    [string, bigint, KycReviewDecision],
    Result_20
  >,
  'adminRunPayoutCycle' : ActorMethod<[string], Result_5>,
  'adminStartKycReview' : ActorMethod<[string, bigint], Result_20>,
  'adminUpdateConfig' : ActorMethod<[string, AppConfig], Result_19>,
  'browseListings' : ActorMethod<[BrowseFilter], Array<PublicListing>>,
  'completeOnboarding' : ActorMethod<[string, OnboardingProfile], Result_18>,
  'confirmCheckout' : ActorMethod<[string, string, boolean], Result_17>,
  'createListing' : ActorMethod<[string, ListingInput], Result_1>,
  'createSupportTicket' : ActorMethod<[string, TicketInput], Result_16>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getKycState' : ActorMethod<[string], Result_3>,
  'getListingDetail' : ActorMethod<[bigint], Result_15>,
  'getMe' : ActorMethod<[string], Result_14>,
  'getMyBankAccounts' : ActorMethod<[string], Result_13>,
  'getMyListing' : ActorMethod<[string, bigint], Result_1>,
  'getMyListings' : ActorMethod<[string], Result_12>,
  'getMyNotifications' : ActorMethod<[string], Result_11>,
  'getMyOrders' : ActorMethod<[string], Result_8>,
  'getMyPayouts' : ActorMethod<[string], Result_10>,
  'getMySupportTickets' : ActorMethod<[string], Result_9>,
  'getOrder' : ActorMethod<[string, bigint], Result_2>,
  'getPublicConfig' : ActorMethod<[], PublicConfig>,
  'getSellerOrders' : ActorMethod<[string], Result_8>,
  'initiateCheckout' : ActorMethod<[string, CheckoutInput], Result_7>,
  'logout' : ActorMethod<[string], undefined>,
  'lookupIfsc' : ActorMethod<[string], Result_6>,
  'manageListing' : ActorMethod<
    [string, bigint, SellerListingAction],
    Result_1
  >,
  'markAllNotificationsRead' : ActorMethod<[string], Result_5>,
  'markNotificationRead' : ActorMethod<[string, bigint], Result_5>,
  'sendOtp' : ActorMethod<[string], Result_4>,
  'submitKycDocument' : ActorMethod<[string, KycSubmission], Result_3>,
  'submitListingForPublish' : ActorMethod<[string, bigint], Result_1>,
  'transitionOrderStatus' : ActorMethod<
    [string, bigint, OrderStatus],
    Result_2
  >,
  'updateListing' : ActorMethod<[string, bigint, ListingInput], Result_1>,
  'verifyOtp' : ActorMethod<[string, string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];