/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddGroupMessageInput = IDL.Record({
  'content' : IDL.Text,
  'authorId' : IDL.Nat,
  'groupId' : IDL.Nat,
  'isVoiceMessage' : IDL.Bool,
});
export const GroupMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'authorId' : IDL.Nat,
  'groupId' : IDL.Nat,
  'isVoiceMessage' : IDL.Bool,
  'timestamp' : IDL.Int,
});
export const DisputeStatus = IDL.Variant({
  'UnderReview' : IDL.Null,
  'Open' : IDL.Null,
  'Escalated' : IDL.Null,
  'Resolved' : IDL.Null,
});
export const DisputeEvent = IDL.Record({
  'event' : IDL.Text,
  'performedBy' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const DisputeCase = IDL.Record({
  'id' : IDL.Nat,
  'status' : DisputeStatus,
  'resolution' : IDL.Opt(IDL.Text),
  'orderId' : IDL.Nat,
  'evidence' : IDL.Vec(IDL.Text),
  'timeline' : IDL.Vec(DisputeEvent),
});
export const ForumReply = IDL.Record({
  'body' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ForumPost = IDL.Record({
  'id' : IDL.Nat,
  'upvotes' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'author' : IDL.Text,
  'replies' : IDL.Vec(ForumReply),
});
export const KycVerificationStatus = IDL.Variant({
  'Rejected' : IDL.Null,
  'Verified' : IDL.Null,
  'Pending' : IDL.Null,
});
export const AuditEvent = IDL.Record({
  'action' : IDL.Text,
  'performedBy' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const KycRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : KycVerificationStatus,
  'selfieVerified' : IDL.Bool,
  'idVerified' : IDL.Bool,
  'auditEvents' : IDL.Vec(AuditEvent),
  'userId' : IDL.Nat,
});
export const ContractType = IDL.Variant({
  'None' : IDL.Null,
  'Phytosanitary' : IDL.Null,
  'Rental' : IDL.Null,
});
export const PayoutSchedule = IDL.Variant({
  'Net30' : IDL.Null,
  'Weekly' : IDL.Null,
  'Daily' : IDL.Null,
});
export const ProduceCategory = IDL.Variant({
  'Eggs' : IDL.Null,
  'Grains' : IDL.Null,
  'Dairy' : IDL.Null,
  'Vegetables' : IDL.Null,
  'Other' : IDL.Null,
  'Fruits' : IDL.Null,
});
export const VerificationStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Expired' : IDL.Null,
  'Pending' : IDL.Null,
});
export const CreateSellerListingInput = IDL.Record({
  'farmerId' : IDL.Nat,
  'name' : IDL.Text,
  'contractType' : ContractType,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'bulkUploadBatch' : IDL.Text,
  'payoutSchedule' : PayoutSchedule,
  'category' : ProduceCategory,
  'certifications' : IDL.Vec(IDL.Text),
  'price' : IDL.Float64,
  'escrowEnabled' : IDL.Bool,
  'verificationStatus' : VerificationStatus,
});
export const SellerListing = IDL.Record({
  'id' : IDL.Nat,
  'farmerId' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'contractType' : ContractType,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'bulkUploadBatch' : IDL.Text,
  'payoutSchedule' : PayoutSchedule,
  'category' : ProduceCategory,
  'rating' : IDL.Float64,
  'certifications' : IDL.Vec(IDL.Text),
  'price' : IDL.Float64,
  'escrowEnabled' : IDL.Bool,
  'verificationStatus' : VerificationStatus,
});
export const CreateCourseInput = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'educatorId' : IDL.Nat,
  'description' : IDL.Text,
  'level' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'isCertified' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : IDL.Int,
  'educatorId' : IDL.Nat,
  'description' : IDL.Text,
  'level' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'isCertified' : IDL.Bool,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
  'enrollmentCount' : IDL.Nat,
});
export const CreateListingInput = IDL.Record({
  'farmerId' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : ProduceCategory,
  'price' : IDL.Float64,
  'escrowEnabled' : IDL.Bool,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'farmerId' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : ProduceCategory,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
  'escrowEnabled' : IDL.Bool,
});
export const CreateLiveStreamInput = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'hostId' : IDL.Nat,
  'scheduledAt' : IDL.Int,
});
export const StreamStatus = IDL.Variant({
  'Ended' : IDL.Null,
  'Live' : IDL.Null,
  'Scheduled' : IDL.Null,
});
export const LiveStream = IDL.Record({
  'id' : IDL.Nat,
  'status' : StreamStatus,
  'title' : IDL.Text,
  'startedAt' : IDL.Opt(IDL.Int),
  'thumbnailUrl' : IDL.Text,
  'endedAt' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'hostId' : IDL.Nat,
  'viewerCount' : IDL.Nat,
  'scheduledAt' : IDL.Int,
});
export const NotifType = IDL.Variant({
  'SystemAlert' : IDL.Null,
  'Transaction' : IDL.Null,
  'MarketIntelligence' : IDL.Null,
  'Educational' : IDL.Null,
  'Emergency' : IDL.Null,
});
export const NotifPriority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Critical' : IDL.Null,
});
export const CreateNotificationInput = IDL.Record({
  'title' : IDL.Text,
  'notifType' : NotifType,
  'body' : IDL.Text,
  'userId' : IDL.Nat,
  'priority' : NotifPriority,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'notifType' : NotifType,
  'body' : IDL.Text,
  'userId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'priority' : NotifPriority,
});
export const CreateQuestionInput = IDL.Record({
  'title' : IDL.Text,
  'authorId' : IDL.Nat,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'upvoteCount' : IDL.Nat,
  'authorId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'answerCount' : IDL.Nat,
  'category' : IDL.Text,
});
export const CreateReelInput = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'farmerId' : IDL.Nat,
  'linkedListingId' : IDL.Opt(IDL.Nat),
});
export const Reel = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'farmerId' : IDL.Nat,
  'viewCount' : IDL.Nat,
  'linkedListingId' : IDL.Opt(IDL.Nat),
});
export const CreateEnrollmentInput = IDL.Record({
  'userId' : IDL.Nat,
  'courseId' : IDL.Nat,
});
export const Enrollment = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : IDL.Opt(IDL.Int),
  'userId' : IDL.Nat,
  'progress' : IDL.Float64,
  'enrolledAt' : IDL.Int,
  'courseId' : IDL.Nat,
});
export const AlertType = IDL.Variant({
  'Pest' : IDL.Null,
  'Weather' : IDL.Null,
});
export const AlertSeverity = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Critical' : IDL.Null,
});
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'alertType' : AlertType,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'severity' : AlertSeverity,
  'location' : IDL.Text,
});
export const Answer = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'upvoteCount' : IDL.Nat,
  'authorId' : IDL.Nat,
  'questionId' : IDL.Nat,
});
export const Certification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'badgeUrl' : IDL.Text,
  'userId' : IDL.Nat,
  'issuedAt' : IDL.Int,
  'courseId' : IDL.Nat,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'lastMessageAt' : IDL.Int,
  'lastMessage' : IDL.Text,
  'unreadCount' : IDL.Nat,
  'participantIds' : IDL.Vec(IDL.Nat),
});
export const DirectMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'isRead' : IDL.Bool,
  'isVoiceMessage' : IDL.Bool,
  'receiverId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'senderId' : IDL.Nat,
});
export const KycStatus = IDL.Variant({
  'Unverified' : IDL.Null,
  'Verified' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Educator = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'courseCount' : IDL.Nat,
  'name' : IDL.Text,
  'specialty' : IDL.Text,
  'kycStatus' : KycStatus,
  'avatarUrl' : IDL.Text,
  'rating' : IDL.Float64,
  'studentCount' : IDL.Nat,
});
export const Farmer = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'numListings' : IDL.Nat,
  'name' : IDL.Text,
  'kycStatus' : KycStatus,
  'avatarUrl' : IDL.Text,
  'rating' : IDL.Float64,
  'location' : IDL.Text,
});
export const Group = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'memberCount' : IDL.Nat,
  'description' : IDL.Text,
  'iconUrl' : IDL.Text,
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
  'videoUrl' : IDL.Text,
  'courseId' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'Disputed' : IDL.Null,
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'total' : IDL.Float64,
  'listingId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'buyerId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const LogisticsListing = IDL.Record({
  'id' : IDL.Nat,
  'serviceArea' : IDL.Text,
  'ratePerKm' : IDL.Float64,
  'imageUrl' : IDL.Text,
  'providerName' : IDL.Text,
});
export const ExpertProfile = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'hourlyRate' : IDL.Float64,
  'available' : IDL.Bool,
  'specialty' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const MachineryListing = IDL.Record({
  'id' : IDL.Nat,
  'dailyRate' : IDL.Float64,
  'ownerId' : IDL.Nat,
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const MaintenanceEntry = IDL.Record({
  'technician' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
});
export const EquipmentGuide = IDL.Record({
  'id' : IDL.Nat,
  'compatibility' : IDL.Vec(IDL.Text),
  'equipmentName' : IDL.Text,
  'maintenanceLog' : IDL.Vec(MaintenanceEntry),
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'threshold' : IDL.Nat,
  'listingId' : IDL.Nat,
  'forecastDays' : IDL.Nat,
  'currentStock' : IDL.Nat,
});
export const MarketPriceTick = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'cropName' : IDL.Text,
  'price' : IDL.Float64,
  'changePercent' : IDL.Float64,
});
export const MarketPrice = IDL.Record({
  'id' : IDL.Nat,
  'region' : IDL.Text,
  'crop' : IDL.Text,
  'date' : IDL.Int,
  'bidPrice' : IDL.Float64,
  'askPrice' : IDL.Float64,
});
export const PlantingEntry = IDL.Record({
  'id' : IDL.Nat,
  'plantDate' : IDL.Int,
  'notes' : IDL.Text,
  'cropName' : IDL.Text,
  'harvestDate' : IDL.Int,
});
export const SalesPeriod = IDL.Variant({
  'Weekly' : IDL.Null,
  'Daily' : IDL.Null,
  'Monthly' : IDL.Null,
  'Yearly' : IDL.Null,
});
export const SalesAnalytics = IDL.Record({
  'id' : IDL.Nat,
  'period' : SalesPeriod,
  'cropName' : IDL.Text,
  'totalRevenue' : IDL.Float64,
  'unitsSold' : IDL.Nat,
});
export const SeasonalAlertType = IDL.Variant({
  'Pest' : IDL.Null,
  'Price' : IDL.Null,
  'Weather' : IDL.Null,
});
export const SeasonalAlert = IDL.Record({
  'id' : IDL.Nat,
  'region' : IDL.Text,
  'alertType' : SeasonalAlertType,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'cropName' : IDL.Text,
  'severity' : AlertSeverity,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Nat,
  'permissions' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
  'lastActive' : IDL.Int,
});
export const CreateDirectMessageInput = IDL.Record({
  'content' : IDL.Text,
  'isVoiceMessage' : IDL.Bool,
  'receiverId' : IDL.Nat,
  'senderId' : IDL.Nat,
});
export const SubmitOrderInput = IDL.Record({
  'total' : IDL.Float64,
  'listingId' : IDL.Nat,
  'buyerId' : IDL.Nat,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addGroupMessage' : IDL.Func([AddGroupMessageInput], [GroupMessage], []),
  'add_dispute_case' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Text)],
      [DisputeCase],
      [],
    ),
  'add_forum_post' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ForumPost], []),
  'add_kyc_record' : IDL.Func([IDL.Nat], [KycRecord], []),
  'add_seller_listing' : IDL.Func(
      [CreateSellerListingInput],
      [SellerListing],
      [],
    ),
  'createCourse' : IDL.Func([CreateCourseInput], [Course], []),
  'createListing' : IDL.Func([CreateListingInput], [Listing], []),
  'createLiveStream' : IDL.Func([CreateLiveStreamInput], [LiveStream], []),
  'createNotification' : IDL.Func(
      [CreateNotificationInput],
      [Notification],
      [],
    ),
  'createQuestion' : IDL.Func([CreateQuestionInput], [Question], []),
  'createReel' : IDL.Func([CreateReelInput], [Reel], []),
  'enrollInCourse' : IDL.Func([CreateEnrollmentInput], [Enrollment], []),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAnswers' : IDL.Func([IDL.Nat], [IDL.Vec(Answer)], ['query']),
  'getCertificationsByUser' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Certification)],
      ['query'],
    ),
  'getConversations' : IDL.Func([IDL.Nat], [IDL.Vec(Conversation)], ['query']),
  'getCourseById' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getDirectMessages' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DirectMessage)],
      ['query'],
    ),
  'getEducatorById' : IDL.Func([IDL.Nat], [IDL.Opt(Educator)], ['query']),
  'getEducators' : IDL.Func([], [IDL.Vec(Educator)], ['query']),
  'getEnrollmentsByUser' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Enrollment)],
      ['query'],
    ),
  'getFarmers' : IDL.Func([], [IDL.Vec(Farmer)], ['query']),
  'getGroupMessages' : IDL.Func([IDL.Nat], [IDL.Vec(GroupMessage)], ['query']),
  'getGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getLessonsByCourse' : IDL.Func([IDL.Nat], [IDL.Vec(Lesson)], ['query']),
  'getListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getLiveStreams' : IDL.Func([], [IDL.Vec(LiveStream)], ['query']),
  'getNotifications' : IDL.Func([IDL.Nat], [IDL.Vec(Notification)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getQA' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
  'getServices' : IDL.Func(
      [],
      [
        IDL.Record({
          'logistics' : IDL.Vec(LogisticsListing),
          'experts' : IDL.Vec(ExpertProfile),
          'machinery' : IDL.Vec(MachineryListing),
        }),
      ],
      ['query'],
    ),
  'get_dispute_cases' : IDL.Func([], [IDL.Vec(DisputeCase)], ['query']),
  'get_equipment_guides' : IDL.Func([], [IDL.Vec(EquipmentGuide)], ['query']),
  'get_forum_posts' : IDL.Func([], [IDL.Vec(ForumPost)], ['query']),
  'get_inventory_items' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'get_kyc_records' : IDL.Func([], [IDL.Vec(KycRecord)], ['query']),
  'get_market_price_ticks' : IDL.Func(
      [],
      [IDL.Vec(MarketPriceTick)],
      ['query'],
    ),
  'get_market_prices' : IDL.Func([], [IDL.Vec(MarketPrice)], ['query']),
  'get_planting_entries' : IDL.Func([], [IDL.Vec(PlantingEntry)], ['query']),
  'get_sales_analytics' : IDL.Func([], [IDL.Vec(SalesAnalytics)], ['query']),
  'get_seasonal_alerts' : IDL.Func([], [IDL.Vec(SeasonalAlert)], ['query']),
  'get_seller_listing' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SellerListing)],
      ['query'],
    ),
  'get_seller_listings' : IDL.Func([], [IDL.Vec(SellerListing)], ['query']),
  'get_team_members' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'sendDirectMessage' : IDL.Func(
      [CreateDirectMessageInput],
      [DirectMessage],
      [],
    ),
  'submitOrder' : IDL.Func([SubmitOrderInput], [Order], []),
  'update_kyc_status' : IDL.Func(
      [IDL.Nat, KycVerificationStatus],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddGroupMessageInput = IDL.Record({
    'content' : IDL.Text,
    'authorId' : IDL.Nat,
    'groupId' : IDL.Nat,
    'isVoiceMessage' : IDL.Bool,
  });
  const GroupMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'authorId' : IDL.Nat,
    'groupId' : IDL.Nat,
    'isVoiceMessage' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  const DisputeStatus = IDL.Variant({
    'UnderReview' : IDL.Null,
    'Open' : IDL.Null,
    'Escalated' : IDL.Null,
    'Resolved' : IDL.Null,
  });
  const DisputeEvent = IDL.Record({
    'event' : IDL.Text,
    'performedBy' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const DisputeCase = IDL.Record({
    'id' : IDL.Nat,
    'status' : DisputeStatus,
    'resolution' : IDL.Opt(IDL.Text),
    'orderId' : IDL.Nat,
    'evidence' : IDL.Vec(IDL.Text),
    'timeline' : IDL.Vec(DisputeEvent),
  });
  const ForumReply = IDL.Record({
    'body' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ForumPost = IDL.Record({
    'id' : IDL.Nat,
    'upvotes' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'author' : IDL.Text,
    'replies' : IDL.Vec(ForumReply),
  });
  const KycVerificationStatus = IDL.Variant({
    'Rejected' : IDL.Null,
    'Verified' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const AuditEvent = IDL.Record({
    'action' : IDL.Text,
    'performedBy' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const KycRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : KycVerificationStatus,
    'selfieVerified' : IDL.Bool,
    'idVerified' : IDL.Bool,
    'auditEvents' : IDL.Vec(AuditEvent),
    'userId' : IDL.Nat,
  });
  const ContractType = IDL.Variant({
    'None' : IDL.Null,
    'Phytosanitary' : IDL.Null,
    'Rental' : IDL.Null,
  });
  const PayoutSchedule = IDL.Variant({
    'Net30' : IDL.Null,
    'Weekly' : IDL.Null,
    'Daily' : IDL.Null,
  });
  const ProduceCategory = IDL.Variant({
    'Eggs' : IDL.Null,
    'Grains' : IDL.Null,
    'Dairy' : IDL.Null,
    'Vegetables' : IDL.Null,
    'Other' : IDL.Null,
    'Fruits' : IDL.Null,
  });
  const VerificationStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Expired' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const CreateSellerListingInput = IDL.Record({
    'farmerId' : IDL.Nat,
    'name' : IDL.Text,
    'contractType' : ContractType,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'bulkUploadBatch' : IDL.Text,
    'payoutSchedule' : PayoutSchedule,
    'category' : ProduceCategory,
    'certifications' : IDL.Vec(IDL.Text),
    'price' : IDL.Float64,
    'escrowEnabled' : IDL.Bool,
    'verificationStatus' : VerificationStatus,
  });
  const SellerListing = IDL.Record({
    'id' : IDL.Nat,
    'farmerId' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'contractType' : ContractType,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'bulkUploadBatch' : IDL.Text,
    'payoutSchedule' : PayoutSchedule,
    'category' : ProduceCategory,
    'rating' : IDL.Float64,
    'certifications' : IDL.Vec(IDL.Text),
    'price' : IDL.Float64,
    'escrowEnabled' : IDL.Bool,
    'verificationStatus' : VerificationStatus,
  });
  const CreateCourseInput = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'educatorId' : IDL.Nat,
    'description' : IDL.Text,
    'level' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'isCertified' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : IDL.Int,
    'educatorId' : IDL.Nat,
    'description' : IDL.Text,
    'level' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'isCertified' : IDL.Bool,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
    'enrollmentCount' : IDL.Nat,
  });
  const CreateListingInput = IDL.Record({
    'farmerId' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : ProduceCategory,
    'price' : IDL.Float64,
    'escrowEnabled' : IDL.Bool,
  });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'farmerId' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : ProduceCategory,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
    'escrowEnabled' : IDL.Bool,
  });
  const CreateLiveStreamInput = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'hostId' : IDL.Nat,
    'scheduledAt' : IDL.Int,
  });
  const StreamStatus = IDL.Variant({
    'Ended' : IDL.Null,
    'Live' : IDL.Null,
    'Scheduled' : IDL.Null,
  });
  const LiveStream = IDL.Record({
    'id' : IDL.Nat,
    'status' : StreamStatus,
    'title' : IDL.Text,
    'startedAt' : IDL.Opt(IDL.Int),
    'thumbnailUrl' : IDL.Text,
    'endedAt' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'hostId' : IDL.Nat,
    'viewerCount' : IDL.Nat,
    'scheduledAt' : IDL.Int,
  });
  const NotifType = IDL.Variant({
    'SystemAlert' : IDL.Null,
    'Transaction' : IDL.Null,
    'MarketIntelligence' : IDL.Null,
    'Educational' : IDL.Null,
    'Emergency' : IDL.Null,
  });
  const NotifPriority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const CreateNotificationInput = IDL.Record({
    'title' : IDL.Text,
    'notifType' : NotifType,
    'body' : IDL.Text,
    'userId' : IDL.Nat,
    'priority' : NotifPriority,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'notifType' : NotifType,
    'body' : IDL.Text,
    'userId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'priority' : NotifPriority,
  });
  const CreateQuestionInput = IDL.Record({
    'title' : IDL.Text,
    'authorId' : IDL.Nat,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'upvoteCount' : IDL.Nat,
    'authorId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'answerCount' : IDL.Nat,
    'category' : IDL.Text,
  });
  const CreateReelInput = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'farmerId' : IDL.Nat,
    'linkedListingId' : IDL.Opt(IDL.Nat),
  });
  const Reel = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'farmerId' : IDL.Nat,
    'viewCount' : IDL.Nat,
    'linkedListingId' : IDL.Opt(IDL.Nat),
  });
  const CreateEnrollmentInput = IDL.Record({
    'userId' : IDL.Nat,
    'courseId' : IDL.Nat,
  });
  const Enrollment = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : IDL.Opt(IDL.Int),
    'userId' : IDL.Nat,
    'progress' : IDL.Float64,
    'enrolledAt' : IDL.Int,
    'courseId' : IDL.Nat,
  });
  const AlertType = IDL.Variant({ 'Pest' : IDL.Null, 'Weather' : IDL.Null });
  const AlertSeverity = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'alertType' : AlertType,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'severity' : AlertSeverity,
    'location' : IDL.Text,
  });
  const Answer = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'upvoteCount' : IDL.Nat,
    'authorId' : IDL.Nat,
    'questionId' : IDL.Nat,
  });
  const Certification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'badgeUrl' : IDL.Text,
    'userId' : IDL.Nat,
    'issuedAt' : IDL.Int,
    'courseId' : IDL.Nat,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'lastMessageAt' : IDL.Int,
    'lastMessage' : IDL.Text,
    'unreadCount' : IDL.Nat,
    'participantIds' : IDL.Vec(IDL.Nat),
  });
  const DirectMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'isRead' : IDL.Bool,
    'isVoiceMessage' : IDL.Bool,
    'receiverId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'senderId' : IDL.Nat,
  });
  const KycStatus = IDL.Variant({
    'Unverified' : IDL.Null,
    'Verified' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Educator = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'courseCount' : IDL.Nat,
    'name' : IDL.Text,
    'specialty' : IDL.Text,
    'kycStatus' : KycStatus,
    'avatarUrl' : IDL.Text,
    'rating' : IDL.Float64,
    'studentCount' : IDL.Nat,
  });
  const Farmer = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'numListings' : IDL.Nat,
    'name' : IDL.Text,
    'kycStatus' : KycStatus,
    'avatarUrl' : IDL.Text,
    'rating' : IDL.Float64,
    'location' : IDL.Text,
  });
  const Group = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'memberCount' : IDL.Nat,
    'description' : IDL.Text,
    'iconUrl' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
    'videoUrl' : IDL.Text,
    'courseId' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'Disputed' : IDL.Null,
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'total' : IDL.Float64,
    'listingId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'buyerId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const LogisticsListing = IDL.Record({
    'id' : IDL.Nat,
    'serviceArea' : IDL.Text,
    'ratePerKm' : IDL.Float64,
    'imageUrl' : IDL.Text,
    'providerName' : IDL.Text,
  });
  const ExpertProfile = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'hourlyRate' : IDL.Float64,
    'available' : IDL.Bool,
    'specialty' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const MachineryListing = IDL.Record({
    'id' : IDL.Nat,
    'dailyRate' : IDL.Float64,
    'ownerId' : IDL.Nat,
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const MaintenanceEntry = IDL.Record({
    'technician' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
  });
  const EquipmentGuide = IDL.Record({
    'id' : IDL.Nat,
    'compatibility' : IDL.Vec(IDL.Text),
    'equipmentName' : IDL.Text,
    'maintenanceLog' : IDL.Vec(MaintenanceEntry),
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'threshold' : IDL.Nat,
    'listingId' : IDL.Nat,
    'forecastDays' : IDL.Nat,
    'currentStock' : IDL.Nat,
  });
  const MarketPriceTick = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'cropName' : IDL.Text,
    'price' : IDL.Float64,
    'changePercent' : IDL.Float64,
  });
  const MarketPrice = IDL.Record({
    'id' : IDL.Nat,
    'region' : IDL.Text,
    'crop' : IDL.Text,
    'date' : IDL.Int,
    'bidPrice' : IDL.Float64,
    'askPrice' : IDL.Float64,
  });
  const PlantingEntry = IDL.Record({
    'id' : IDL.Nat,
    'plantDate' : IDL.Int,
    'notes' : IDL.Text,
    'cropName' : IDL.Text,
    'harvestDate' : IDL.Int,
  });
  const SalesPeriod = IDL.Variant({
    'Weekly' : IDL.Null,
    'Daily' : IDL.Null,
    'Monthly' : IDL.Null,
    'Yearly' : IDL.Null,
  });
  const SalesAnalytics = IDL.Record({
    'id' : IDL.Nat,
    'period' : SalesPeriod,
    'cropName' : IDL.Text,
    'totalRevenue' : IDL.Float64,
    'unitsSold' : IDL.Nat,
  });
  const SeasonalAlertType = IDL.Variant({
    'Pest' : IDL.Null,
    'Price' : IDL.Null,
    'Weather' : IDL.Null,
  });
  const SeasonalAlert = IDL.Record({
    'id' : IDL.Nat,
    'region' : IDL.Text,
    'alertType' : SeasonalAlertType,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'cropName' : IDL.Text,
    'severity' : AlertSeverity,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Nat,
    'permissions' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
    'lastActive' : IDL.Int,
  });
  const CreateDirectMessageInput = IDL.Record({
    'content' : IDL.Text,
    'isVoiceMessage' : IDL.Bool,
    'receiverId' : IDL.Nat,
    'senderId' : IDL.Nat,
  });
  const SubmitOrderInput = IDL.Record({
    'total' : IDL.Float64,
    'listingId' : IDL.Nat,
    'buyerId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    'addGroupMessage' : IDL.Func([AddGroupMessageInput], [GroupMessage], []),
    'add_dispute_case' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Text)],
        [DisputeCase],
        [],
      ),
    'add_forum_post' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ForumPost],
        [],
      ),
    'add_kyc_record' : IDL.Func([IDL.Nat], [KycRecord], []),
    'add_seller_listing' : IDL.Func(
        [CreateSellerListingInput],
        [SellerListing],
        [],
      ),
    'createCourse' : IDL.Func([CreateCourseInput], [Course], []),
    'createListing' : IDL.Func([CreateListingInput], [Listing], []),
    'createLiveStream' : IDL.Func([CreateLiveStreamInput], [LiveStream], []),
    'createNotification' : IDL.Func(
        [CreateNotificationInput],
        [Notification],
        [],
      ),
    'createQuestion' : IDL.Func([CreateQuestionInput], [Question], []),
    'createReel' : IDL.Func([CreateReelInput], [Reel], []),
    'enrollInCourse' : IDL.Func([CreateEnrollmentInput], [Enrollment], []),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAnswers' : IDL.Func([IDL.Nat], [IDL.Vec(Answer)], ['query']),
    'getCertificationsByUser' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Certification)],
        ['query'],
      ),
    'getConversations' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Conversation)],
        ['query'],
      ),
    'getCourseById' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getDirectMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getEducatorById' : IDL.Func([IDL.Nat], [IDL.Opt(Educator)], ['query']),
    'getEducators' : IDL.Func([], [IDL.Vec(Educator)], ['query']),
    'getEnrollmentsByUser' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Enrollment)],
        ['query'],
      ),
    'getFarmers' : IDL.Func([], [IDL.Vec(Farmer)], ['query']),
    'getGroupMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(GroupMessage)],
        ['query'],
      ),
    'getGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getLessonsByCourse' : IDL.Func([IDL.Nat], [IDL.Vec(Lesson)], ['query']),
    'getListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getLiveStreams' : IDL.Func([], [IDL.Vec(LiveStream)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getQA' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
    'getServices' : IDL.Func(
        [],
        [
          IDL.Record({
            'logistics' : IDL.Vec(LogisticsListing),
            'experts' : IDL.Vec(ExpertProfile),
            'machinery' : IDL.Vec(MachineryListing),
          }),
        ],
        ['query'],
      ),
    'get_dispute_cases' : IDL.Func([], [IDL.Vec(DisputeCase)], ['query']),
    'get_equipment_guides' : IDL.Func([], [IDL.Vec(EquipmentGuide)], ['query']),
    'get_forum_posts' : IDL.Func([], [IDL.Vec(ForumPost)], ['query']),
    'get_inventory_items' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'get_kyc_records' : IDL.Func([], [IDL.Vec(KycRecord)], ['query']),
    'get_market_price_ticks' : IDL.Func(
        [],
        [IDL.Vec(MarketPriceTick)],
        ['query'],
      ),
    'get_market_prices' : IDL.Func([], [IDL.Vec(MarketPrice)], ['query']),
    'get_planting_entries' : IDL.Func([], [IDL.Vec(PlantingEntry)], ['query']),
    'get_sales_analytics' : IDL.Func([], [IDL.Vec(SalesAnalytics)], ['query']),
    'get_seasonal_alerts' : IDL.Func([], [IDL.Vec(SeasonalAlert)], ['query']),
    'get_seller_listing' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SellerListing)],
        ['query'],
      ),
    'get_seller_listings' : IDL.Func([], [IDL.Vec(SellerListing)], ['query']),
    'get_team_members' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'sendDirectMessage' : IDL.Func(
        [CreateDirectMessageInput],
        [DirectMessage],
        [],
      ),
    'submitOrder' : IDL.Func([SubmitOrderInput], [Order], []),
    'update_kyc_status' : IDL.Func(
        [IDL.Nat, KycVerificationStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };