/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DisputeEvent {
    event: string;
    performedBy: string;
    timestamp: bigint;
}
export interface GroupMessage {
    id: bigint;
    content: string;
    authorId: bigint;
    groupId: bigint;
    isVoiceMessage: boolean;
    timestamp: bigint;
}
export interface CreateLiveStreamInput {
    title: string;
    thumbnailUrl: string;
    description: string;
    hostId: bigint;
    scheduledAt: bigint;
}
export interface CreateDirectMessageInput {
    content: string;
    isVoiceMessage: boolean;
    receiverId: bigint;
    senderId: bigint;
}
export interface AddGroupMessageInput {
    content: string;
    authorId: bigint;
    groupId: bigint;
    isVoiceMessage: boolean;
}
export interface DisputeCase {
    id: bigint;
    status: DisputeStatus;
    resolution?: string;
    orderId: bigint;
    evidence: Array<string>;
    timeline: Array<DisputeEvent>;
}
export interface InventoryItem {
    id: bigint;
    threshold: bigint;
    listingId: bigint;
    forecastDays: bigint;
    currentStock: bigint;
}
export interface AuditEvent {
    action: string;
    performedBy: string;
    timestamp: bigint;
}
export interface Lesson {
    id: bigint;
    title: string;
    content: string;
    order: bigint;
    durationMinutes: bigint;
    videoUrl: string;
    courseId: bigint;
}
export interface KycRecord {
    id: bigint;
    status: KycVerificationStatus;
    selfieVerified: boolean;
    idVerified: boolean;
    auditEvents: Array<AuditEvent>;
    userId: bigint;
}
export interface CreateSellerListingInput {
    farmerId: bigint;
    name: string;
    contractType: ContractType;
    description: string;
    imageUrl: string;
    bulkUploadBatch: string;
    payoutSchedule: PayoutSchedule;
    category: ProduceCategory;
    certifications: Array<string>;
    price: number;
    escrowEnabled: boolean;
    verificationStatus: VerificationStatus;
}
export interface MarketPriceTick {
    id: bigint;
    date: bigint;
    cropName: string;
    price: number;
    changePercent: number;
}
export interface SalesAnalytics {
    id: bigint;
    period: SalesPeriod;
    cropName: string;
    totalRevenue: number;
    unitsSold: bigint;
}
export interface SellerListing {
    id: bigint;
    farmerId: bigint;
    name: string;
    createdAt: bigint;
    contractType: ContractType;
    description: string;
    imageUrl: string;
    bulkUploadBatch: string;
    payoutSchedule: PayoutSchedule;
    category: ProduceCategory;
    rating: number;
    certifications: Array<string>;
    price: number;
    escrowEnabled: boolean;
    verificationStatus: VerificationStatus;
}
export interface ForumPost {
    id: bigint;
    upvotes: bigint;
    title: string;
    body: string;
    author: string;
    replies: Array<ForumReply>;
}
export interface Farmer {
    id: bigint;
    bio: string;
    numListings: bigint;
    name: string;
    kycStatus: KycStatus;
    avatarUrl: string;
    rating: number;
    location: string;
}
export interface LogisticsListing {
    id: bigint;
    serviceArea: string;
    ratePerKm: number;
    imageUrl: string;
    providerName: string;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    total: number;
    listingId: bigint;
    createdAt: bigint;
    buyerId: bigint;
    quantity: bigint;
}
export interface CreateNotificationInput {
    title: string;
    notifType: NotifType;
    body: string;
    userId: bigint;
    priority: NotifPriority;
}
export interface SeasonalAlert {
    id: bigint;
    region: string;
    alertType: SeasonalAlertType;
    title: string;
    description: string;
    timestamp: bigint;
    cropName: string;
    severity: AlertSeverity;
}
export interface Certification {
    id: bigint;
    title: string;
    badgeUrl: string;
    userId: bigint;
    issuedAt: bigint;
    courseId: bigint;
}
export interface MarketPrice {
    id: bigint;
    region: string;
    crop: string;
    date: bigint;
    bidPrice: number;
    askPrice: number;
}
export interface Notification {
    id: bigint;
    title: string;
    notifType: NotifType;
    body: string;
    userId: bigint;
    createdAt: bigint;
    isRead: boolean;
    priority: NotifPriority;
}
export interface Conversation {
    id: bigint;
    lastMessageAt: bigint;
    lastMessage: string;
    unreadCount: bigint;
    participantIds: Array<bigint>;
}
export interface PlantingEntry {
    id: bigint;
    plantDate: bigint;
    notes: string;
    cropName: string;
    harvestDate: bigint;
}
export interface LiveStream {
    id: bigint;
    status: StreamStatus;
    title: string;
    startedAt?: bigint;
    thumbnailUrl: string;
    endedAt?: bigint;
    description: string;
    hostId: bigint;
    viewerCount: bigint;
    scheduledAt: bigint;
}
export interface Reel {
    id: bigint;
    title: string;
    thumbnailUrl: string;
    farmerId: bigint;
    viewCount: bigint;
    linkedListingId?: bigint;
}
export interface MaintenanceEntry {
    technician: string;
    date: bigint;
    description: string;
}
export interface Enrollment {
    id: bigint;
    completedAt?: bigint;
    userId: bigint;
    progress: number;
    enrolledAt: bigint;
    courseId: bigint;
}
export interface Group {
    id: bigint;
    name: string;
    memberCount: bigint;
    description: string;
    iconUrl: string;
}
export interface EquipmentGuide {
    id: bigint;
    compatibility: Array<string>;
    equipmentName: string;
    maintenanceLog: Array<MaintenanceEntry>;
}
export interface CreateReelInput {
    title: string;
    thumbnailUrl: string;
    farmerId: bigint;
    linkedListingId?: bigint;
}
export interface Course {
    id: bigint;
    title: string;
    thumbnailUrl: string;
    createdAt: bigint;
    educatorId: bigint;
    description: string;
    level: string;
    durationMinutes: bigint;
    isCertified: boolean;
    category: string;
    rating: number;
    price: number;
    enrollmentCount: bigint;
}
export interface Educator {
    id: bigint;
    bio: string;
    courseCount: bigint;
    name: string;
    specialty: string;
    kycStatus: KycStatus;
    avatarUrl: string;
    rating: number;
    studentCount: bigint;
}
export interface CreateQuestionInput {
    title: string;
    authorId: bigint;
    description: string;
    category: string;
}
export interface CreateCourseInput {
    title: string;
    thumbnailUrl: string;
    educatorId: bigint;
    description: string;
    level: string;
    durationMinutes: bigint;
    isCertified: boolean;
    category: string;
    price: number;
}
export interface ExpertProfile {
    id: bigint;
    name: string;
    hourlyRate: number;
    available: boolean;
    specialty: string;
    imageUrl: string;
}
export interface Alert {
    id: bigint;
    alertType: AlertType;
    title: string;
    description: string;
    timestamp: bigint;
    severity: AlertSeverity;
    location: string;
}
export interface DirectMessage {
    id: bigint;
    content: string;
    isRead: boolean;
    isVoiceMessage: boolean;
    receiverId: bigint;
    timestamp: bigint;
    senderId: bigint;
}
export interface Listing {
    id: bigint;
    farmerId: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    imageUrl: string;
    category: ProduceCategory;
    rating: number;
    price: number;
    escrowEnabled: boolean;
}
export interface CreateListingInput {
    farmerId: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: ProduceCategory;
    price: number;
    escrowEnabled: boolean;
}
export interface ForumReply {
    body: string;
    author: string;
    timestamp: bigint;
}
export interface MachineryListing {
    id: bigint;
    dailyRate: number;
    ownerId: bigint;
    name: string;
    available: boolean;
    imageUrl: string;
    category: string;
}
export interface SubmitOrderInput {
    total: number;
    listingId: bigint;
    buyerId: bigint;
    quantity: bigint;
}
export interface Answer {
    id: bigint;
    content: string;
    upvoteCount: bigint;
    authorId: bigint;
    questionId: bigint;
}
export interface TeamMember {
    id: bigint;
    permissions: Array<string>;
    name: string;
    role: string;
    lastActive: bigint;
}
export interface Question {
    id: bigint;
    title: string;
    upvoteCount: bigint;
    authorId: bigint;
    createdAt: bigint;
    description: string;
    answerCount: bigint;
    category: string;
}
export interface CreateEnrollmentInput {
    userId: bigint;
    courseId: bigint;
}
export enum AlertType {
    Pest = "Pest",
    Weather = "Weather"
}
export enum ContractType {
    None = "None",
    Phytosanitary = "Phytosanitary",
    Rental = "Rental"
}
export enum DisputeStatus {
    UnderReview = "UnderReview",
    Open = "Open",
    Escalated = "Escalated",
    Resolved = "Resolved"
}
export enum KycStatus {
    Unverified = "Unverified",
    Verified = "Verified",
    Pending = "Pending"
}
export enum KycVerificationStatus {
    Rejected = "Rejected",
    Verified = "Verified",
    Pending = "Pending"
}
export enum NotifPriority {
    Low = "Low",
    High = "High",
    Medium = "Medium",
    Critical = "Critical"
}
export enum NotifType {
    SystemAlert = "SystemAlert",
    Transaction = "Transaction",
    MarketIntelligence = "MarketIntelligence",
    Educational = "Educational",
    Emergency = "Emergency"
}
export enum OrderStatus {
    Disputed = "Disputed",
    Delivered = "Delivered",
    Confirmed = "Confirmed",
    Shipped = "Shipped",
    Pending = "Pending"
}
export enum PayoutSchedule {
    Net30 = "Net30",
    Weekly = "Weekly",
    Daily = "Daily"
}
export enum ProduceCategory {
    Eggs = "Eggs",
    Grains = "Grains",
    Dairy = "Dairy",
    Vegetables = "Vegetables",
    Other = "Other",
    Fruits = "Fruits"
}
export enum SalesPeriod {
    Weekly = "Weekly",
    Daily = "Daily",
    Monthly = "Monthly",
    Yearly = "Yearly"
}
export enum SeasonalAlertType {
    Pest = "Pest",
    Price = "Price",
    Weather = "Weather"
}
export enum StreamStatus {
    Ended = "Ended",
    Live = "Live",
    Scheduled = "Scheduled"
}
export enum VerificationStatus {
    Approved = "Approved",
    Expired = "Expired",
    Pending = "Pending"
}
export interface backendInterface {
    addGroupMessage(input: AddGroupMessageInput): Promise<GroupMessage>;
    add_dispute_case(orderId: bigint, evidence: Array<string>): Promise<DisputeCase>;
    add_forum_post(author: string, title: string, body: string): Promise<ForumPost>;
    add_kyc_record(userId: bigint): Promise<KycRecord>;
    add_seller_listing(input: CreateSellerListingInput): Promise<SellerListing>;
    createCourse(input: CreateCourseInput): Promise<Course>;
    createListing(input: CreateListingInput): Promise<Listing>;
    createLiveStream(input: CreateLiveStreamInput): Promise<LiveStream>;
    createNotification(input: CreateNotificationInput): Promise<Notification>;
    createQuestion(input: CreateQuestionInput): Promise<Question>;
    createReel(input: CreateReelInput): Promise<Reel>;
    enrollInCourse(input: CreateEnrollmentInput): Promise<Enrollment>;
    getAlerts(): Promise<Array<Alert>>;
    getAnswers(questionId: bigint): Promise<Array<Answer>>;
    getCertificationsByUser(userId: bigint): Promise<Array<Certification>>;
    getConversations(userId: bigint): Promise<Array<Conversation>>;
    getCourseById(id: bigint): Promise<Course | null>;
    getCourses(): Promise<Array<Course>>;
    getDirectMessages(conversationId: bigint): Promise<Array<DirectMessage>>;
    getEducatorById(id: bigint): Promise<Educator | null>;
    getEducators(): Promise<Array<Educator>>;
    getEnrollmentsByUser(userId: bigint): Promise<Array<Enrollment>>;
    getFarmers(): Promise<Array<Farmer>>;
    getGroupMessages(groupId: bigint): Promise<Array<GroupMessage>>;
    getGroups(): Promise<Array<Group>>;
    getLessonsByCourse(courseId: bigint): Promise<Array<Lesson>>;
    getListings(): Promise<Array<Listing>>;
    getLiveStreams(): Promise<Array<LiveStream>>;
    getNotifications(userId: bigint): Promise<Array<Notification>>;
    getOrders(): Promise<Array<Order>>;
    getQA(): Promise<Array<Question>>;
    getReels(): Promise<Array<Reel>>;
    getServices(): Promise<{
        logistics: Array<LogisticsListing>;
        experts: Array<ExpertProfile>;
        machinery: Array<MachineryListing>;
    }>;
    get_dispute_cases(): Promise<Array<DisputeCase>>;
    get_equipment_guides(): Promise<Array<EquipmentGuide>>;
    get_forum_posts(): Promise<Array<ForumPost>>;
    get_inventory_items(): Promise<Array<InventoryItem>>;
    get_kyc_records(): Promise<Array<KycRecord>>;
    get_market_price_ticks(): Promise<Array<MarketPriceTick>>;
    get_market_prices(): Promise<Array<MarketPrice>>;
    get_planting_entries(): Promise<Array<PlantingEntry>>;
    get_sales_analytics(): Promise<Array<SalesAnalytics>>;
    get_seasonal_alerts(): Promise<Array<SeasonalAlert>>;
    get_seller_listing(id: bigint): Promise<SellerListing | null>;
    get_seller_listings(): Promise<Array<SellerListing>>;
    get_team_members(): Promise<Array<TeamMember>>;
    markNotificationRead(notifId: bigint): Promise<boolean>;
    sendDirectMessage(input: CreateDirectMessageInput): Promise<DirectMessage>;
    submitOrder(input: SubmitOrderInput): Promise<Order>;
    update_kyc_status(id: bigint, status: KycVerificationStatus): Promise<boolean>;
}
import type { Alert as _Alert, AlertSeverity as _AlertSeverity, AlertType as _AlertType, AuditEvent as _AuditEvent, ContractType as _ContractType, Course as _Course, CreateListingInput as _CreateListingInput, CreateNotificationInput as _CreateNotificationInput, CreateReelInput as _CreateReelInput, CreateSellerListingInput as _CreateSellerListingInput, DisputeCase as _DisputeCase, DisputeEvent as _DisputeEvent, DisputeStatus as _DisputeStatus, Educator as _Educator, Enrollment as _Enrollment, Farmer as _Farmer, KycRecord as _KycRecord, KycStatus as _KycStatus, KycVerificationStatus as _KycVerificationStatus, Listing as _Listing, LiveStream as _LiveStream, NotifPriority as _NotifPriority, NotifType as _NotifType, Notification as _Notification, Order as _Order, OrderStatus as _OrderStatus, PayoutSchedule as _PayoutSchedule, ProduceCategory as _ProduceCategory, Reel as _Reel, SalesAnalytics as _SalesAnalytics, SalesPeriod as _SalesPeriod, SeasonalAlert as _SeasonalAlert, SeasonalAlertType as _SeasonalAlertType, SellerListing as _SellerListing, StreamStatus as _StreamStatus, VerificationStatus as _VerificationStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGroupMessage(arg0: AddGroupMessageInput): Promise<GroupMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroupMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroupMessage(arg0);
            return result;
        }
    }
    async add_dispute_case(arg0: bigint, arg1: Array<string>): Promise<DisputeCase> {
        if (this.processError) {
            try {
                const result = await this.actor.add_dispute_case(arg0, arg1);
                return from_candid_DisputeCase_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.add_dispute_case(arg0, arg1);
            return from_candid_DisputeCase_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async add_forum_post(arg0: string, arg1: string, arg2: string): Promise<ForumPost> {
        if (this.processError) {
            try {
                const result = await this.actor.add_forum_post(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.add_forum_post(arg0, arg1, arg2);
            return result;
        }
    }
    async add_kyc_record(arg0: bigint): Promise<KycRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.add_kyc_record(arg0);
                return from_candid_KycRecord_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.add_kyc_record(arg0);
            return from_candid_KycRecord_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async add_seller_listing(arg0: CreateSellerListingInput): Promise<SellerListing> {
        if (this.processError) {
            try {
                const result = await this.actor.add_seller_listing(to_candid_CreateSellerListingInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SellerListing_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.add_seller_listing(to_candid_CreateSellerListingInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SellerListing_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCourse(arg0: CreateCourseInput): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0);
            return result;
        }
    }
    async createListing(arg0: CreateListingInput): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(to_candid_CreateListingInput_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Listing_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(to_candid_CreateListingInput_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Listing_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLiveStream(arg0: CreateLiveStreamInput): Promise<LiveStream> {
        if (this.processError) {
            try {
                const result = await this.actor.createLiveStream(arg0);
                return from_candid_LiveStream_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLiveStream(arg0);
            return from_candid_LiveStream_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNotification(arg0: CreateNotificationInput): Promise<Notification> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(to_candid_CreateNotificationInput_n39(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Notification_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(to_candid_CreateNotificationInput_n39(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Notification_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async createQuestion(arg0: CreateQuestionInput): Promise<Question> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuestion(arg0);
            return result;
        }
    }
    async createReel(arg0: CreateReelInput): Promise<Reel> {
        if (this.processError) {
            try {
                const result = await this.actor.createReel(to_candid_CreateReelInput_n51(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Reel_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReel(to_candid_CreateReelInput_n51(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Reel_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async enrollInCourse(arg0: CreateEnrollmentInput): Promise<Enrollment> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollInCourse(arg0);
                return from_candid_Enrollment_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollInCourse(arg0);
            return from_candid_Enrollment_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnswers(arg0: bigint): Promise<Array<Answer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnswers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnswers(arg0);
            return result;
        }
    }
    async getCertificationsByUser(arg0: bigint): Promise<Array<Certification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertificationsByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertificationsByUser(arg0);
            return result;
        }
    }
    async getConversations(arg0: bigint): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations(arg0);
            return result;
        }
    }
    async getCourseById(arg0: bigint): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseById(arg0);
                return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseById(arg0);
            return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourses();
            return result;
        }
    }
    async getDirectMessages(arg0: bigint): Promise<Array<DirectMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDirectMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDirectMessages(arg0);
            return result;
        }
    }
    async getEducatorById(arg0: bigint): Promise<Educator | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEducatorById(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEducatorById(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEducators(): Promise<Array<Educator>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEducators();
                return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEducators();
            return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnrollmentsByUser(arg0: bigint): Promise<Array<Enrollment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnrollmentsByUser(arg0);
                return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnrollmentsByUser(arg0);
            return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarmers(): Promise<Array<Farmer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmers();
                return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmers();
            return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupMessages(arg0: bigint): Promise<Array<GroupMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupMessages(arg0);
            return result;
        }
    }
    async getGroups(): Promise<Array<Group>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroups();
            return result;
        }
    }
    async getLessonsByCourse(arg0: bigint): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonsByCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonsByCourse(arg0);
            return result;
        }
    }
    async getListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListings();
                return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListings();
            return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLiveStreams(): Promise<Array<LiveStream>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveStreams();
                return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveStreams();
            return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: bigint): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0);
                return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0);
            return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQA(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQA();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQA();
            return result;
        }
    }
    async getReels(): Promise<Array<Reel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReels();
                return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReels();
            return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServices(): Promise<{
        logistics: Array<LogisticsListing>;
        experts: Array<ExpertProfile>;
        machinery: Array<MachineryListing>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServices();
            return result;
        }
    }
    async get_dispute_cases(): Promise<Array<DisputeCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_dispute_cases();
                return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_dispute_cases();
            return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_equipment_guides(): Promise<Array<EquipmentGuide>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_equipment_guides();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_equipment_guides();
            return result;
        }
    }
    async get_forum_posts(): Promise<Array<ForumPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_forum_posts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_forum_posts();
            return result;
        }
    }
    async get_inventory_items(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_inventory_items();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_inventory_items();
            return result;
        }
    }
    async get_kyc_records(): Promise<Array<KycRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_kyc_records();
                return from_candid_vec_n85(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_kyc_records();
            return from_candid_vec_n85(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_market_price_ticks(): Promise<Array<MarketPriceTick>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_market_price_ticks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_market_price_ticks();
            return result;
        }
    }
    async get_market_prices(): Promise<Array<MarketPrice>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_market_prices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_market_prices();
            return result;
        }
    }
    async get_planting_entries(): Promise<Array<PlantingEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_planting_entries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_planting_entries();
            return result;
        }
    }
    async get_sales_analytics(): Promise<Array<SalesAnalytics>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_sales_analytics();
                return from_candid_vec_n86(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_sales_analytics();
            return from_candid_vec_n86(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_seasonal_alerts(): Promise<Array<SeasonalAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_seasonal_alerts();
                return from_candid_vec_n91(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_seasonal_alerts();
            return from_candid_vec_n91(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_seller_listing(arg0: bigint): Promise<SellerListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.get_seller_listing(arg0);
                return from_candid_opt_n96(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_seller_listing(arg0);
            return from_candid_opt_n96(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_seller_listings(): Promise<Array<SellerListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_seller_listings();
                return from_candid_vec_n97(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_seller_listings();
            return from_candid_vec_n97(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_team_members(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_team_members();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_team_members();
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async sendDirectMessage(arg0: CreateDirectMessageInput): Promise<DirectMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendDirectMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendDirectMessage(arg0);
            return result;
        }
    }
    async submitOrder(arg0: SubmitOrderInput): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOrder(arg0);
                return from_candid_Order_n79(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOrder(arg0);
            return from_candid_Order_n79(this._uploadFile, this._downloadFile, result);
        }
    }
    async update_kyc_status(arg0: bigint, arg1: KycVerificationStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.update_kyc_status(arg0, to_candid_KycVerificationStatus_n98(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_kyc_status(arg0, to_candid_KycVerificationStatus_n98(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AlertSeverity_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertSeverity): AlertSeverity {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_AlertType_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertType): AlertType {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Alert_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_ContractType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContractType): ContractType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_DisputeCase_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisputeCase): DisputeCase {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_DisputeStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisputeStatus): DisputeStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Educator_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Educator): Educator {
    return from_candid_record_n67(_uploadFile, _downloadFile, value);
}
function from_candid_Enrollment_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enrollment): Enrollment {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Farmer_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Farmer): Farmer {
    return from_candid_record_n74(_uploadFile, _downloadFile, value);
}
function from_candid_KycRecord_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KycRecord): KycRecord {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_KycStatus_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KycStatus): KycStatus {
    return from_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function from_candid_KycVerificationStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KycVerificationStatus): KycVerificationStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Listing_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Listing {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_LiveStream_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiveStream): LiveStream {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_NotifPriority_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotifPriority): NotifPriority {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_NotifType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotifType): NotifType {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n82(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n80(_uploadFile, _downloadFile, value);
}
function from_candid_PayoutSchedule_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutSchedule): PayoutSchedule {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ProduceCategory_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProduceCategory): ProduceCategory {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Reel_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reel): Reel {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_SalesAnalytics_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesAnalytics): SalesAnalytics {
    return from_candid_record_n88(_uploadFile, _downloadFile, value);
}
function from_candid_SalesPeriod_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesPeriod): SalesPeriod {
    return from_candid_variant_n90(_uploadFile, _downloadFile, value);
}
function from_candid_SeasonalAlertType_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SeasonalAlertType): SeasonalAlertType {
    return from_candid_variant_n95(_uploadFile, _downloadFile, value);
}
function from_candid_SeasonalAlert_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SeasonalAlert): SeasonalAlert {
    return from_candid_record_n93(_uploadFile, _downloadFile, value);
}
function from_candid_SellerListing_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SellerListing): SellerListing {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_StreamStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StreamStatus): StreamStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Educator]): Educator | null {
    return value.length === 0 ? null : from_candid_Educator_n66(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SellerListing]): SellerListing | null {
    return value.length === 0 ? null : from_candid_SellerListing_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DisputeStatus;
    resolution: [] | [string];
    orderId: bigint;
    evidence: Array<string>;
    timeline: Array<_DisputeEvent>;
}): {
    id: bigint;
    status: DisputeStatus;
    resolution?: string;
    orderId: bigint;
    evidence: Array<string>;
    timeline: Array<DisputeEvent>;
} {
    return {
        id: value.id,
        status: from_candid_DisputeStatus_n3(_uploadFile, _downloadFile, value.status),
        resolution: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.resolution)),
        orderId: value.orderId,
        evidence: value.evidence,
        timeline: value.timeline
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    farmerId: bigint;
    name: string;
    createdAt: bigint;
    contractType: _ContractType;
    description: string;
    imageUrl: string;
    bulkUploadBatch: string;
    payoutSchedule: _PayoutSchedule;
    category: _ProduceCategory;
    rating: number;
    certifications: Array<string>;
    price: number;
    escrowEnabled: boolean;
    verificationStatus: _VerificationStatus;
}): {
    id: bigint;
    farmerId: bigint;
    name: string;
    createdAt: bigint;
    contractType: ContractType;
    description: string;
    imageUrl: string;
    bulkUploadBatch: string;
    payoutSchedule: PayoutSchedule;
    category: ProduceCategory;
    rating: number;
    certifications: Array<string>;
    price: number;
    escrowEnabled: boolean;
    verificationStatus: VerificationStatus;
} {
    return {
        id: value.id,
        farmerId: value.farmerId,
        name: value.name,
        createdAt: value.createdAt,
        contractType: from_candid_ContractType_n22(_uploadFile, _downloadFile, value.contractType),
        description: value.description,
        imageUrl: value.imageUrl,
        bulkUploadBatch: value.bulkUploadBatch,
        payoutSchedule: from_candid_PayoutSchedule_n24(_uploadFile, _downloadFile, value.payoutSchedule),
        category: from_candid_ProduceCategory_n26(_uploadFile, _downloadFile, value.category),
        rating: value.rating,
        certifications: value.certifications,
        price: value.price,
        escrowEnabled: value.escrowEnabled,
        verificationStatus: from_candid_VerificationStatus_n28(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    farmerId: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    imageUrl: string;
    category: _ProduceCategory;
    rating: number;
    price: number;
    escrowEnabled: boolean;
}): {
    id: bigint;
    farmerId: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    imageUrl: string;
    category: ProduceCategory;
    rating: number;
    price: number;
    escrowEnabled: boolean;
} {
    return {
        id: value.id,
        farmerId: value.farmerId,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        imageUrl: value.imageUrl,
        category: from_candid_ProduceCategory_n26(_uploadFile, _downloadFile, value.category),
        rating: value.rating,
        price: value.price,
        escrowEnabled: value.escrowEnabled
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _StreamStatus;
    title: string;
    startedAt: [] | [bigint];
    thumbnailUrl: string;
    endedAt: [] | [bigint];
    description: string;
    hostId: bigint;
    viewerCount: bigint;
    scheduledAt: bigint;
}): {
    id: bigint;
    status: StreamStatus;
    title: string;
    startedAt?: bigint;
    thumbnailUrl: string;
    endedAt?: bigint;
    description: string;
    hostId: bigint;
    viewerCount: bigint;
    scheduledAt: bigint;
} {
    return {
        id: value.id,
        status: from_candid_StreamStatus_n36(_uploadFile, _downloadFile, value.status),
        title: value.title,
        startedAt: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.startedAt)),
        thumbnailUrl: value.thumbnailUrl,
        endedAt: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.endedAt)),
        description: value.description,
        hostId: value.hostId,
        viewerCount: value.viewerCount,
        scheduledAt: value.scheduledAt
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    notifType: _NotifType;
    body: string;
    userId: bigint;
    createdAt: bigint;
    isRead: boolean;
    priority: _NotifPriority;
}): {
    id: bigint;
    title: string;
    notifType: NotifType;
    body: string;
    userId: bigint;
    createdAt: bigint;
    isRead: boolean;
    priority: NotifPriority;
} {
    return {
        id: value.id,
        title: value.title,
        notifType: from_candid_NotifType_n47(_uploadFile, _downloadFile, value.notifType),
        body: value.body,
        userId: value.userId,
        createdAt: value.createdAt,
        isRead: value.isRead,
        priority: from_candid_NotifPriority_n49(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    thumbnailUrl: string;
    farmerId: bigint;
    viewCount: bigint;
    linkedListingId: [] | [bigint];
}): {
    id: bigint;
    title: string;
    thumbnailUrl: string;
    farmerId: bigint;
    viewCount: bigint;
    linkedListingId?: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        thumbnailUrl: value.thumbnailUrl,
        farmerId: value.farmerId,
        viewCount: value.viewCount,
        linkedListingId: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.linkedListingId))
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    completedAt: [] | [bigint];
    userId: bigint;
    progress: number;
    enrolledAt: bigint;
    courseId: bigint;
}): {
    id: bigint;
    completedAt?: bigint;
    userId: bigint;
    progress: number;
    enrolledAt: bigint;
    courseId: bigint;
} {
    return {
        id: value.id,
        completedAt: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.completedAt)),
        userId: value.userId,
        progress: value.progress,
        enrolledAt: value.enrolledAt,
        courseId: value.courseId
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    alertType: _AlertType;
    title: string;
    description: string;
    timestamp: bigint;
    severity: _AlertSeverity;
    location: string;
}): {
    id: bigint;
    alertType: AlertType;
    title: string;
    description: string;
    timestamp: bigint;
    severity: AlertSeverity;
    location: string;
} {
    return {
        id: value.id,
        alertType: from_candid_AlertType_n61(_uploadFile, _downloadFile, value.alertType),
        title: value.title,
        description: value.description,
        timestamp: value.timestamp,
        severity: from_candid_AlertSeverity_n63(_uploadFile, _downloadFile, value.severity),
        location: value.location
    };
}
function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bio: string;
    courseCount: bigint;
    name: string;
    specialty: string;
    kycStatus: _KycStatus;
    avatarUrl: string;
    rating: number;
    studentCount: bigint;
}): {
    id: bigint;
    bio: string;
    courseCount: bigint;
    name: string;
    specialty: string;
    kycStatus: KycStatus;
    avatarUrl: string;
    rating: number;
    studentCount: bigint;
} {
    return {
        id: value.id,
        bio: value.bio,
        courseCount: value.courseCount,
        name: value.name,
        specialty: value.specialty,
        kycStatus: from_candid_KycStatus_n68(_uploadFile, _downloadFile, value.kycStatus),
        avatarUrl: value.avatarUrl,
        rating: value.rating,
        studentCount: value.studentCount
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _KycVerificationStatus;
    selfieVerified: boolean;
    idVerified: boolean;
    auditEvents: Array<_AuditEvent>;
    userId: bigint;
}): {
    id: bigint;
    status: KycVerificationStatus;
    selfieVerified: boolean;
    idVerified: boolean;
    auditEvents: Array<AuditEvent>;
    userId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_KycVerificationStatus_n8(_uploadFile, _downloadFile, value.status),
        selfieVerified: value.selfieVerified,
        idVerified: value.idVerified,
        auditEvents: value.auditEvents,
        userId: value.userId
    };
}
function from_candid_record_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bio: string;
    numListings: bigint;
    name: string;
    kycStatus: _KycStatus;
    avatarUrl: string;
    rating: number;
    location: string;
}): {
    id: bigint;
    bio: string;
    numListings: bigint;
    name: string;
    kycStatus: KycStatus;
    avatarUrl: string;
    rating: number;
    location: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        numListings: value.numListings,
        name: value.name,
        kycStatus: from_candid_KycStatus_n68(_uploadFile, _downloadFile, value.kycStatus),
        avatarUrl: value.avatarUrl,
        rating: value.rating,
        location: value.location
    };
}
function from_candid_record_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    total: number;
    listingId: bigint;
    createdAt: bigint;
    buyerId: bigint;
    quantity: bigint;
}): {
    id: bigint;
    status: OrderStatus;
    total: number;
    listingId: bigint;
    createdAt: bigint;
    buyerId: bigint;
    quantity: bigint;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n81(_uploadFile, _downloadFile, value.status),
        total: value.total,
        listingId: value.listingId,
        createdAt: value.createdAt,
        buyerId: value.buyerId,
        quantity: value.quantity
    };
}
function from_candid_record_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    period: _SalesPeriod;
    cropName: string;
    totalRevenue: number;
    unitsSold: bigint;
}): {
    id: bigint;
    period: SalesPeriod;
    cropName: string;
    totalRevenue: number;
    unitsSold: bigint;
} {
    return {
        id: value.id,
        period: from_candid_SalesPeriod_n89(_uploadFile, _downloadFile, value.period),
        cropName: value.cropName,
        totalRevenue: value.totalRevenue,
        unitsSold: value.unitsSold
    };
}
function from_candid_record_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    region: string;
    alertType: _SeasonalAlertType;
    title: string;
    description: string;
    timestamp: bigint;
    cropName: string;
    severity: _AlertSeverity;
}): {
    id: bigint;
    region: string;
    alertType: SeasonalAlertType;
    title: string;
    description: string;
    timestamp: bigint;
    cropName: string;
    severity: AlertSeverity;
} {
    return {
        id: value.id,
        region: value.region,
        alertType: from_candid_SeasonalAlertType_n94(_uploadFile, _downloadFile, value.alertType),
        title: value.title,
        description: value.description,
        timestamp: value.timestamp,
        cropName: value.cropName,
        severity: from_candid_AlertSeverity_n63(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    None: null;
} | {
    Phytosanitary: null;
} | {
    Rental: null;
}): ContractType {
    return "None" in value ? ContractType.None : "Phytosanitary" in value ? ContractType.Phytosanitary : "Rental" in value ? ContractType.Rental : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Net30: null;
} | {
    Weekly: null;
} | {
    Daily: null;
}): PayoutSchedule {
    return "Net30" in value ? PayoutSchedule.Net30 : "Weekly" in value ? PayoutSchedule.Weekly : "Daily" in value ? PayoutSchedule.Daily : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Eggs: null;
} | {
    Grains: null;
} | {
    Dairy: null;
} | {
    Vegetables: null;
} | {
    Other: null;
} | {
    Fruits: null;
}): ProduceCategory {
    return "Eggs" in value ? ProduceCategory.Eggs : "Grains" in value ? ProduceCategory.Grains : "Dairy" in value ? ProduceCategory.Dairy : "Vegetables" in value ? ProduceCategory.Vegetables : "Other" in value ? ProduceCategory.Other : "Fruits" in value ? ProduceCategory.Fruits : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Expired: null;
} | {
    Pending: null;
}): VerificationStatus {
    return "Approved" in value ? VerificationStatus.Approved : "Expired" in value ? VerificationStatus.Expired : "Pending" in value ? VerificationStatus.Pending : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ended: null;
} | {
    Live: null;
} | {
    Scheduled: null;
}): StreamStatus {
    return "Ended" in value ? StreamStatus.Ended : "Live" in value ? StreamStatus.Live : "Scheduled" in value ? StreamStatus.Scheduled : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UnderReview: null;
} | {
    Open: null;
} | {
    Escalated: null;
} | {
    Resolved: null;
}): DisputeStatus {
    return "UnderReview" in value ? DisputeStatus.UnderReview : "Open" in value ? DisputeStatus.Open : "Escalated" in value ? DisputeStatus.Escalated : "Resolved" in value ? DisputeStatus.Resolved : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SystemAlert: null;
} | {
    Transaction: null;
} | {
    MarketIntelligence: null;
} | {
    Educational: null;
} | {
    Emergency: null;
}): NotifType {
    return "SystemAlert" in value ? NotifType.SystemAlert : "Transaction" in value ? NotifType.Transaction : "MarketIntelligence" in value ? NotifType.MarketIntelligence : "Educational" in value ? NotifType.Educational : "Emergency" in value ? NotifType.Emergency : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Critical: null;
}): NotifPriority {
    return "Low" in value ? NotifPriority.Low : "High" in value ? NotifPriority.High : "Medium" in value ? NotifPriority.Medium : "Critical" in value ? NotifPriority.Critical : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Pest: null;
} | {
    Weather: null;
}): AlertType {
    return "Pest" in value ? AlertType.Pest : "Weather" in value ? AlertType.Weather : value;
}
function from_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Unverified: null;
} | {
    Verified: null;
} | {
    Pending: null;
}): KycStatus {
    return "Unverified" in value ? KycStatus.Unverified : "Verified" in value ? KycStatus.Verified : "Pending" in value ? KycStatus.Pending : value;
}
function from_candid_variant_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Disputed: null;
} | {
    Delivered: null;
} | {
    Confirmed: null;
} | {
    Shipped: null;
} | {
    Pending: null;
}): OrderStatus {
    return "Disputed" in value ? OrderStatus.Disputed : "Delivered" in value ? OrderStatus.Delivered : "Confirmed" in value ? OrderStatus.Confirmed : "Shipped" in value ? OrderStatus.Shipped : "Pending" in value ? OrderStatus.Pending : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Rejected: null;
} | {
    Verified: null;
} | {
    Pending: null;
}): KycVerificationStatus {
    return "Rejected" in value ? KycVerificationStatus.Rejected : "Verified" in value ? KycVerificationStatus.Verified : "Pending" in value ? KycVerificationStatus.Pending : value;
}
function from_candid_variant_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Weekly: null;
} | {
    Daily: null;
} | {
    Monthly: null;
} | {
    Yearly: null;
}): SalesPeriod {
    return "Weekly" in value ? SalesPeriod.Weekly : "Daily" in value ? SalesPeriod.Daily : "Monthly" in value ? SalesPeriod.Monthly : "Yearly" in value ? SalesPeriod.Yearly : value;
}
function from_candid_variant_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Pest: null;
} | {
    Price: null;
} | {
    Weather: null;
}): SeasonalAlertType {
    return "Pest" in value ? SeasonalAlertType.Pest : "Price" in value ? SeasonalAlertType.Price : "Weather" in value ? SeasonalAlertType.Weather : value;
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n59(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Educator>): Array<Educator> {
    return value.map((x)=>from_candid_Educator_n66(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enrollment>): Array<Enrollment> {
    return value.map((x)=>from_candid_Enrollment_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Farmer>): Array<Farmer> {
    return value.map((x)=>from_candid_Farmer_n73(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Array<Listing> {
    return value.map((x)=>from_candid_Listing_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LiveStream>): Array<LiveStream> {
    return value.map((x)=>from_candid_LiveStream_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n79(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reel>): Array<Reel> {
    return value.map((x)=>from_candid_Reel_n53(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DisputeCase>): Array<DisputeCase> {
    return value.map((x)=>from_candid_DisputeCase_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KycRecord>): Array<KycRecord> {
    return value.map((x)=>from_candid_KycRecord_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalesAnalytics>): Array<SalesAnalytics> {
    return value.map((x)=>from_candid_SalesAnalytics_n87(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SeasonalAlert>): Array<SeasonalAlert> {
    return value.map((x)=>from_candid_SeasonalAlert_n92(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SellerListing>): Array<SellerListing> {
    return value.map((x)=>from_candid_SellerListing_n20(_uploadFile, _downloadFile, x));
}
function to_candid_ContractType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContractType): _ContractType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_CreateListingInput_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateListingInput): _CreateListingInput {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_CreateNotificationInput_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateNotificationInput): _CreateNotificationInput {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_CreateReelInput_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateReelInput): _CreateReelInput {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_CreateSellerListingInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateSellerListingInput): _CreateSellerListingInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_KycVerificationStatus_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KycVerificationStatus): _KycVerificationStatus {
    return to_candid_variant_n99(_uploadFile, _downloadFile, value);
}
function to_candid_NotifPriority_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotifPriority): _NotifPriority {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_NotifType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotifType): _NotifType {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_PayoutSchedule_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PayoutSchedule): _PayoutSchedule {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_ProduceCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProduceCategory): _ProduceCategory {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_VerificationStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): _VerificationStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    farmerId: bigint;
    name: string;
    contractType: ContractType;
    description: string;
    imageUrl: string;
    bulkUploadBatch: string;
    payoutSchedule: PayoutSchedule;
    category: ProduceCategory;
    certifications: Array<string>;
    price: number;
    escrowEnabled: boolean;
    verificationStatus: VerificationStatus;
}): {
    farmerId: bigint;
    name: string;
    contractType: _ContractType;
    description: string;
    imageUrl: string;
    bulkUploadBatch: string;
    payoutSchedule: _PayoutSchedule;
    category: _ProduceCategory;
    certifications: Array<string>;
    price: number;
    escrowEnabled: boolean;
    verificationStatus: _VerificationStatus;
} {
    return {
        farmerId: value.farmerId,
        name: value.name,
        contractType: to_candid_ContractType_n12(_uploadFile, _downloadFile, value.contractType),
        description: value.description,
        imageUrl: value.imageUrl,
        bulkUploadBatch: value.bulkUploadBatch,
        payoutSchedule: to_candid_PayoutSchedule_n14(_uploadFile, _downloadFile, value.payoutSchedule),
        category: to_candid_ProduceCategory_n16(_uploadFile, _downloadFile, value.category),
        certifications: value.certifications,
        price: value.price,
        escrowEnabled: value.escrowEnabled,
        verificationStatus: to_candid_VerificationStatus_n18(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    farmerId: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: ProduceCategory;
    price: number;
    escrowEnabled: boolean;
}): {
    farmerId: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: _ProduceCategory;
    price: number;
    escrowEnabled: boolean;
} {
    return {
        farmerId: value.farmerId,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: to_candid_ProduceCategory_n16(_uploadFile, _downloadFile, value.category),
        price: value.price,
        escrowEnabled: value.escrowEnabled
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    notifType: NotifType;
    body: string;
    userId: bigint;
    priority: NotifPriority;
}): {
    title: string;
    notifType: _NotifType;
    body: string;
    userId: bigint;
    priority: _NotifPriority;
} {
    return {
        title: value.title,
        notifType: to_candid_NotifType_n41(_uploadFile, _downloadFile, value.notifType),
        body: value.body,
        userId: value.userId,
        priority: to_candid_NotifPriority_n43(_uploadFile, _downloadFile, value.priority)
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    thumbnailUrl: string;
    farmerId: bigint;
    linkedListingId?: bigint;
}): {
    title: string;
    thumbnailUrl: string;
    farmerId: bigint;
    linkedListingId: [] | [bigint];
} {
    return {
        title: value.title,
        thumbnailUrl: value.thumbnailUrl,
        farmerId: value.farmerId,
        linkedListingId: value.linkedListingId ? candid_some(value.linkedListingId) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContractType): {
    None: null;
} | {
    Phytosanitary: null;
} | {
    Rental: null;
} {
    return value == ContractType.None ? {
        None: null
    } : value == ContractType.Phytosanitary ? {
        Phytosanitary: null
    } : value == ContractType.Rental ? {
        Rental: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PayoutSchedule): {
    Net30: null;
} | {
    Weekly: null;
} | {
    Daily: null;
} {
    return value == PayoutSchedule.Net30 ? {
        Net30: null
    } : value == PayoutSchedule.Weekly ? {
        Weekly: null
    } : value == PayoutSchedule.Daily ? {
        Daily: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProduceCategory): {
    Eggs: null;
} | {
    Grains: null;
} | {
    Dairy: null;
} | {
    Vegetables: null;
} | {
    Other: null;
} | {
    Fruits: null;
} {
    return value == ProduceCategory.Eggs ? {
        Eggs: null
    } : value == ProduceCategory.Grains ? {
        Grains: null
    } : value == ProduceCategory.Dairy ? {
        Dairy: null
    } : value == ProduceCategory.Vegetables ? {
        Vegetables: null
    } : value == ProduceCategory.Other ? {
        Other: null
    } : value == ProduceCategory.Fruits ? {
        Fruits: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): {
    Approved: null;
} | {
    Expired: null;
} | {
    Pending: null;
} {
    return value == VerificationStatus.Approved ? {
        Approved: null
    } : value == VerificationStatus.Expired ? {
        Expired: null
    } : value == VerificationStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotifType): {
    SystemAlert: null;
} | {
    Transaction: null;
} | {
    MarketIntelligence: null;
} | {
    Educational: null;
} | {
    Emergency: null;
} {
    return value == NotifType.SystemAlert ? {
        SystemAlert: null
    } : value == NotifType.Transaction ? {
        Transaction: null
    } : value == NotifType.MarketIntelligence ? {
        MarketIntelligence: null
    } : value == NotifType.Educational ? {
        Educational: null
    } : value == NotifType.Emergency ? {
        Emergency: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotifPriority): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Critical: null;
} {
    return value == NotifPriority.Low ? {
        Low: null
    } : value == NotifPriority.High ? {
        High: null
    } : value == NotifPriority.Medium ? {
        Medium: null
    } : value == NotifPriority.Critical ? {
        Critical: null
    } : value;
}
function to_candid_variant_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KycVerificationStatus): {
    Rejected: null;
} | {
    Verified: null;
} | {
    Pending: null;
} {
    return value == KycVerificationStatus.Rejected ? {
        Rejected: null
    } : value == KycVerificationStatus.Verified ? {
        Verified: null
    } : value == KycVerificationStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
